<!DOCTYPE html>
<!--[if lt IE 7 ]>
<html lang="en" class="no-js oldie ie6" original-class="no-js oldie ie6">
<![endif]--><!--[if IE 7 ]>
<html lang="en" class="no-js oldie ie7" original-class="no-js oldie ie7">
<![endif]--><!--[if IE 8 ]>
<html lang="en" class="no-js oldie ie8" original-class="no-js oldie ie8">
<![endif]--><!--[if IE 9 ]>
<html lang="en" class="no-js ie9" original-class="no-js ie9">
<![endif]--><!--[if (gt IE 9)|!(IE)]><!--><html lang="en" class="no-js" original-class="no-js"><!--[if lt IE 7 ]>
<html lang="en" class="no-js oldie ie6" original-class="no-js oldie ie6">
<![endif]--><!--[if IE 7 ]>
<html lang="en" class="no-js oldie ie7" original-class="no-js oldie ie7">
<![endif]--><!--[if IE 8 ]>
<html lang="en" class="no-js oldie ie8" original-class="no-js oldie ie8">
<![endif]--><!--[if IE 9 ]>
<html lang="en" class="no-js ie9" original-class="no-js ie9">
<![endif]--><!--[if (gt IE 9)|!(IE)]><!--><!--<![endif]-->
<head>
	<!-- Google Tag Manager -->
	<script>
		(function(w, d, s, l, i) {
			w[l] = w[l] || [];
			w[l].push({
				'gtm.start' : new Date().getTime(),
				event : 'gtm.js'
			});
			var f = d.getElementsByTagName(s)[0], j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
			j.async = true;
			j.src = 'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
			f.parentNode.insertBefore(j, f);
		})(window, document, 'script', 'dataLayer', 'GTM-KBVS4S'); 
</script>
	<!-- End Google Tag Manager -->
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="description" content="We are inspired by our patients’ courage, our caregivers’ compassion, and our scientists’ curiosity—all fueled by our donors’ generosity. Imagine what we can do together."><meta property="og:description" content="We are inspired by our patients’ courage, our caregivers’ compassion, and our scientists’ curiosity—all fueled by our donors’ generosity. Imagine what we can do together.">
<!-- generated by seo_lite --><meta property="og:image" content="/sites/all/themes/bwh/img/BWH_About_hero_surgery.jpg?nocdn=1"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><meta property="og:title" content="The BWH Planned Giving Page"><meta name="referrer" content="always"><title><?php print $head_title; ?></title><link rel="shortcut icon" href="/page/-/site/img/favicon.ico"><link rel="apple-touch-icon-precomposed" href="/page/-/site/img/favicon-57x57.png"><meta name="google-site-verification" content="5_34Tkj7nw94wk5ZuA7jYZ0RcVxoKWBQ_uQC_eB-wLA"><!--[if lte IE 8]>
<link rel="stylesheet" href="/sites/all/themes/bwh/css/index-desktop.css">
<![endif]--><!--[if gt IE 8]><!--><link rel="stylesheet" href="/sites/all/themes/bwh/css/index.css"><!--<![endif]--><link rel="stylesheet" href="/sites/all/themes/bwh/css/ss-standard.css"><link rel="stylesheet" href="/sites/all/themes/bwh/css/ss-social-regular.css"><link rel="stylesheet" href="/sites/all/themes/bwh/css/ss-social-circle.css"><script src="/sites/all/themes/bwh/js/jquery.min.js"></script><script src="/sites/all/themes/bwh/js/source-min.js"></script><script src="/sites/all/themes/bwh/js/main.js"></script><script type="text/javascript" src="/sites/all/themes/bwh/js/ss-standard.js"></script><script type="text/javascript" src="/sites/all/themes/bwh/js/ss-social.js"></script><script type="text/javascript" src="/sites/all/themes/bwh/js/ipx5tnj.js"></script><script type="text/javascript">
	try {
		Typekit.load();
	} catch(e) {
	}
</script><!--<script type="text/javascript" src="http://fast.fonts.net/jsapi/074ef5ce-ab0c-4353-9309-8c1cfb07f9e3.js"></script>--><link type="text/css" rel="stylesheet" href="http://fast.fonts.net/cssapi/074ef5ce-ab0c-4353-9309-8c1cfb07f9e3.css"><!-- blue_source_tracking enabled -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta about="/content/what-will-your-legacy-be" property="sioc:num_replies" content="0" datatype="xsd:integer"><link rel="shortcut icon" href="http://bwh.dev.pgdonors.org/sites/default/files/favicon%20%287%29.ico" type="image/vnd.microsoft.icon"><meta content="What Will Your Legacy Be?" about="/content/what-will-your-legacy-be" property="dc:title"><meta name="generator" content="Drupal 7 (http://drupal.org)">
<!--[if IE 7]>
<link rel="stylesheet" href="/sites/all/themes/pgcalc_master/ie7/ie7.css">
<![endif]-->
<?php
print $head;
print $styles;
print $scripts;
?>
<!--[if IE 7]>
<link rel="stylesheet" href="/sites/all/themes/pgcalc_master/ie7/ie7.css">
<![endif]-->
<script type="text/javascript">
	(function() {
		var didInit = false;
		function initMunchkin() {
			if (didInit === false) {
				didInit = true;
				Munchkin.init('266-YFN‌-578');
			}
		}

		var s = document.createElement('script');
		s.type = 'text/javascript';
		s.async = true;
		s.src = '//munchkin.marketo.net/munchkin.js';
		s.onreadystatechange = function() {
			if (this.readyState == 'complete' || this.readyState == 'loaded') {
				initMunchkin();
			}
		};

		s.onload = initMunchkin;
		document.getElementsByTagName('head')[0].appendChild(s);
	})();
</script>
</head>
<?php
print $page_top;
print $page;
print $page_bottom;
?>
</html>
