<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content=""><meta name="author" content=""><link rel="shortcut icon" href="/sites/all/themes/bmm/linked/favicon.png" type="image/png"><title><?php print $head_title; ?></title><meta name="keywords" content="Baptist, missions, mission agency, missionary, missionaries, global, worldwide, ministry, evangelism, church planting "><meta name="description" content="Baptist Mid-Missions is a partner with independent Baptist churches as they send out and equip their members to evangelize and plant new Baptist churches around the world. "><link rel="canonical" href="https://www.bmm.org/give/planned-giving/"><!-- generated by seo_lite --><!-- Bootstrap core CSS --><link href="/sites/all/themes/bmm/css/bootstrap.min.css" rel="stylesheet"><link href="/sites/all/themes/bmm/css/main.css" rel="stylesheet"><!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries --><!--[if lt IE 9]>
 <script src="/sites/all/themes/bmm/js/html5shiv.js"></script>
 <script src="/sites/all/themes/bmm/js/respond.min.js"></script>
 <![endif]-->
<?php
print $head;
print $styles;
print $scripts;
?>
<!--[if IE 7]>
<link rel="stylesheet" href="/sites/all/themes/pgcalc_master/ie7/ie7.css">
<![endif]-->
</head>
<?php
print $page_top;
print $page;
print $page_bottom;
?>
</html>
