<!DOCTYPE html>
<html lang="en-US" class="no-js" original-class="no-js"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"><link rel="profile" href="/sites/all/themes/cardinal/linked/11"><link rel="dns-prefetch" href="//s0.wp.com"><link rel="dns-prefetch" href="//s.w.org"><script type="text/javascript">
 window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/2.2.1\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/2.2.1\/svg\/","svgExt":".svg","source":{"concatemoji":"https:\/\/alumni.cardinalhayes.org\/wp-includes\/js\/wp-emoji-release.min.js?ver=4.7.5"}};
 !function(a,b,c){function d(a){var b,c,d,e,f=String.fromCharCode;if(!k||!k.fillText)return!1;switch(k.clearRect(0,0,j.width,j.height),k.textBaseline="top",k.font="600 32px Arial",a){case"flag":return k.fillText(f(55356,56826,55356,56819),0,0),!(j.toDataURL().length<3e3)&&(k.clearRect(0,0,j.width,j.height),k.fillText(f(55356,57331,65039,8205,55356,57096),0,0),b=j.toDataURL(),k.clearRect(0,0,j.width,j.height),k.fillText(f(55356,57331,55356,57096),0,0),c=j.toDataURL(),b!==c);case"emoji4":return k.fillText(f(55357,56425,55356,57341,8205,55357,56507),0,0),d=j.toDataURL(),k.clearRect(0,0,j.width,j.height),k.fillText(f(55357,56425,55356,57341,55357,56507),0,0),e=j.toDataURL(),d!==e}return!1}function e(a){var c=b.createElement("script");c.src=a,c.defer=c.type="text/javascript",b.getElementsByTagName("head")[0].appendChild(c)}var f,g,h,i,j=b.createElement("canvas"),k=j.getContext&&j.getContext("2d");for(i=Array("flag","emoji4"),c.supports={everything:!0,everythingExceptFlag:!0},h=0;h<i.length;h++)c.supports[i[h]]=d(i[h]),c.supports.everything=c.supports.everything&&c.supports[i[h]],"flag"!==i[h]&&(c.supports.everythingExceptFlag=c.supports.everythingExceptFlag&&c.supports[i[h]]);c.supports.everythingExceptFlag=c.supports.everythingExceptFlag&&!c.supports.flag,c.DOMReady=!1,c.readyCallback=function(){c.DOMReady=!0},c.supports.everything||(g=function(){c.readyCallback()},b.addEventListener?(b.addEventListener("DOMContentLoaded",g,!1),a.addEventListener("load",g,!1)):(a.attachEvent("onload",g),b.attachEvent("onreadystatechange",function(){"complete"===b.readyState&&c.readyCallback()})),f=c.source||{},f.concatemoji?e(f.concatemoji):f.wpemoji&&f.twemoji&&(e(f.twemoji),e(f.wpemoji)))}(window,document,window._wpemojiSettings);
 </script><style type="text/css">
img.wp-smiley,
img.emoji {
 display: inline !important;
 border: none !important;
 box-shadow: none !important;
 height: 1em !important;
 width: 1em !important;
 margin: 0 .07em !important;
 vertical-align: -0.1em !important;
 background: none !important;
 padding: 0 !important;
}
</style><link rel="stylesheet" id="ai1ec_style-css" href="/sites/all/themes/cardinal/css/15e35245_ai1ec_parsed_css.css" type="text/css" media="all"><link rel="stylesheet" id="category-posts-css" href="/sites/all/themes/cardinal/css/cat-posts.css" type="text/css" media="all"><link rel="stylesheet" id="contact-form-7-css" href="/sites/all/themes/cardinal/css/styles.css" type="text/css" media="all"><link rel="stylesheet" id="give-styles-css" href="/sites/all/themes/cardinal/css/give.min.css" type="text/css" media="all"><link rel="stylesheet" id="give_ffm_frontend_styles-css" href="/sites/all/themes/cardinal/css/give-ffm-frontend.min.css" type="text/css" media="all"><link rel="stylesheet" id="give_ffm_datepicker_styles-css" href="/sites/all/themes/cardinal/css/give-ffm-datepicker.min.css" type="text/css" media="all"><link rel="stylesheet" id="resp-video-style-css" href="/sites/all/themes/cardinal/css/respvid.css" type="text/css" media="all"><link rel="stylesheet" id="fontawesome-style-css" href="/sites/all/themes/cardinal/css/font-awesome.min.css" type="text/css" media="all"><link rel="stylesheet" id="flexslider-style-css" href="/sites/all/themes/cardinal/css/flexslider.css" type="text/css" media="all"><link rel="stylesheet" id="accordion-style-css" href="/sites/all/themes/cardinal/css/accordion.css" type="text/css" media="all"><link rel="stylesheet" id="cardinal-style-css" href="/sites/all/themes/cardinal/css/style.css" type="text/css" media="all"><link rel="stylesheet" id="give_recurring_css-css" href="/sites/all/themes/cardinal/css/give-recurring.css" type="text/css" media="all"><link rel="stylesheet" id="cpsh-shortcodes-css" href="/sites/all/themes/cardinal/css/shortcodes.css" type="text/css" media="all"><link rel="stylesheet" id="jetpack_css-css" href="/sites/all/themes/cardinal/css/jetpack.css" type="text/css" media="all"><link rel="stylesheet" id="fasc-buttons-style-css" href="/sites/all/themes/cardinal/css/button-styles.css" type="text/css" media="all"><link rel="stylesheet" id="font-awesome-style-css" href="/sites/all/themes/cardinal/css/5927375a115b4.css" type="text/css" media="all"><script type="text/javascript" src="/sites/all/themes/cardinal/js/jquery.js"></script><script type="text/javascript" src="/sites/all/themes/cardinal/js/jquery-migrate.min.js"></script><script type="text/javascript">
/* <![CDATA[ */
var give_global_vars = {"ajaxurl":"https:\/\/alumni.cardinalhayes.org\/wp-admin\/admin-ajax.php","checkout_nonce":"baacecb338","currency_sign":"$","currency_pos":"before","thousands_separator":",","decimal_separator":".","no_gateway":"Please select a payment method.","bad_minimum":"The minimum donation amount for this form is","general_loading":"Loading...","purchase_loading":"Please Wait...","number_decimals":"0","give_version":"1.8.7.1","magnific_options":{"main_class":"give-modal","close_on_bg_click":false},"form_translation":{"payment-mode":"Please select payment mode.","give_first":"Please enter your first name.","give_email":"Please enter a valid email address.","give_user_login":"Invalid username. Only lowercase letters (a-z) and numbers are allowed.","give_user_pass":"Enter a password.","give_user_pass_confirm":"Enter the password confirmation.","give_agree_to_terms":"You must agree to the terms and conditions."}};
var give_scripts = {"ajaxurl":"https:\/\/alumni.cardinalhayes.org\/wp-admin\/admin-ajax.php","loading":"Loading","select_option":"Please select an option","default_gateway":"paypalpro_payflow","permalinks":"1","number_decimals":"0"};
/* ]]> */
</script><script type="text/javascript" src="/sites/all/themes/cardinal/js/give.all.min.js"></script><script type="text/javascript" src="/sites/all/themes/cardinal/js/core.min.js"></script><script type="text/javascript" src="/sites/all/themes/cardinal/js/datepicker.min.js"></script><script type="text/javascript">
jQuery(document).ready(function(jQuery){jQuery.datepicker.setDefaults({"closeText":"Close","currentText":"Today","monthNames":["January","February","March","April","May","June","July","August","September","October","November","December"],"monthNamesShort":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"nextText":"Next","prevText":"Previous","dayNames":["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],"dayNamesShort":["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],"dayNamesMin":["S","M","T","W","T","F","S"],"dateFormat":"MM d, yy","firstDay":1,"isRTL":false});});
</script><script type="text/javascript" src="/sites/all/themes/cardinal/js/widget.min.js"></script><script type="text/javascript" src="/sites/all/themes/cardinal/js/mouse.min.js"></script><script type="text/javascript" src="/sites/all/themes/cardinal/js/slider.min.js"></script><script type="text/javascript" src="/sites/all/themes/cardinal/js/plupload.full.min.js"></script><script type="text/javascript">
/* <![CDATA[ */
var pluploadL10n = {"queue_limit_exceeded":"You have attempted to queue too many files.","file_exceeds_size_limit":"%s exceeds the maximum upload size for this site.","zero_byte_file":"This file is empty. Please try another.","invalid_filetype":"This file type is not allowed. Please try another.","not_an_image":"This file is not an image. Please try another.","image_memory_exceeded":"Memory exceeded. Please try another smaller file.","image_dimensions_exceeded":"This is larger than the maximum size. Please try another.","default_error":"An error occurred in the upload. Please try again later.","missing_upload_url":"There was a configuration error. Please contact the server administrator.","upload_limit_exceeded":"You may only upload 1 file.","http_error":"HTTP error.","upload_failed":"Upload failed.","big_upload_failed":"Please try uploading this file with the %1$sbrowser uploader%2$s.","big_upload_queued":"%s exceeds the maximum upload size for the multi-file uploader when used in your browser.","io_error":"IO error.","security_error":"Security error.","file_cancelled":"File canceled.","upload_stopped":"Upload stopped.","dismiss":"Dismiss","crunching":"Crunching\u2026","deleted":"moved to the trash.","error_uploading":"\u201c%s\u201d has failed to upload."};
/* ]]> */
</script><script type="text/javascript" src="/sites/all/themes/cardinal/js/handlers.min.js"></script><script type="text/javascript">
/* <![CDATA[ */
var give_ffm_frontend = {"ajaxurl":"https:\/\/alumni.cardinalhayes.org\/wp-admin\/admin-ajax.php","error_message":"Please complete all required fields","nonce":"e006e96781","confirmMsg":"Are you sure?","plupload":{"url":"https:\/\/alumni.cardinalhayes.org\/wp-admin\/admin-ajax.php?nonce=46fd755dfe","flash_swf_url":"https:\/\/alumni.cardinalhayes.org\/wp-includes\/js\/plupload\/plupload.flash.swf","filters":[{"title":"Allowed Files","extensions":"*"}],"multipart":true,"urlstream_upload":true}};
var give_ffm_frontend = {"ajaxurl":"https:\/\/alumni.cardinalhayes.org\/wp-admin\/admin-ajax.php","error_message":"Please complete all required fields","nonce":"e006e96781","confirmMsg":"Are you sure?","plupload":{"url":"https:\/\/alumni.cardinalhayes.org\/wp-admin\/admin-ajax.php?nonce=46fd755dfe","flash_swf_url":"https:\/\/alumni.cardinalhayes.org\/wp-includes\/js\/plupload\/plupload.flash.swf","filters":[{"title":"Allowed Files","extensions":"*"}],"multipart":true,"urlstream_upload":true}};
/* ]]> */
</script><script type="text/javascript" src="/sites/all/themes/cardinal/js/give-ffm-frontend.min.js"></script><script type="text/javascript">
/* <![CDATA[ */
var Give_Recurring_Vars = {"email_access":"1","messages":{"confirm_cancel":"Are you sure you want to cancel this subscription?"}};
/* ]]> */
</script><script type="text/javascript" src="/sites/all/themes/cardinal/js/give-recurring.js"></script><script type="text/javascript" src="/sites/all/themes/cardinal/js/script.js"></script><script type="text/javascript" src="/sites/all/themes/cardinal/js/reservations.js"></script><link rel="https://api.w.org/" href="/sites/all/themes/cardinal/linked/wp-json"><link rel="EditURI" type="application/rsd+xml" title="RSD" href="/sites/all/themes/cardinal/linked/xmlrpc.php"><link rel="wlwmanifest" type="application/wlwmanifest+xml" href="/sites/all/themes/cardinal/linked/wlwmanifest.xml"><meta name="generator" content="WordPress 4.7.5"><link rel="canonical" href="https://alumni.cardinalhayes.org/forever-hayes-campaign/"><link rel="shortlink" href="https://wp.me/P7UOyD-1Q"><link rel="alternate" type="application/json+oembed" href="/sites/all/themes/cardinal/linked/wp-jsonoembed/1.0/embed?url=https%3A%2F%2Falumni.cardinalhayes.org%2Fforever-hayes-campaign%2F"><link rel="alternate" type="text/xml+oembed" href="/sites/all/themes/cardinal/linked/wp-jsonoembed/1.0/embed?url=https%3A%2F%2Falumni.cardinalhayes.org%2Fforever-hayes-campaign%2F&amp;format=xml"><meta name="generator" content="Give v1.8.7.1"><link rel="dns-prefetch" href="//v0.wordpress.com"><link rel="dns-prefetch" href="//i0.wp.com"><link rel="dns-prefetch" href="//i1.wp.com"><link rel="dns-prefetch" href="//i2.wp.com"><style type="text/css">img#wpstats{display:none}</style><script src="/sites/all/themes/cardinal/js/jquery-ui.js"></script><script> var currentPageName = 'forever-hayes-campaign';
 var currentPostType = 'default';
 var domainName = 'alumni.cardinalhayes.org'; 
 var facebookAppID = 'TBD via backend'; 
 var _GLOBAL_THEME_URL = 'https://alumni.cardinalhayes.org/wp-content/themes/cardinalhayes/'; 
 var _SITE_URL = 'https://alumni.cardinalhayes.org';</script><!-- Jetpack Open Graph Tags --><meta property="og:type" content="article"><meta property="og:title" content="Forever Hayes Campaign"><meta property="og:url" content="https://alumni.cardinalhayes.org/forever-hayes-campaign/"><meta property="og:description" content="Beginning in 2009, Cardinal Hayes was made an independent school from the Archdiocese. While the Archdiocese remains committed to the success of CHHS, they are unable to provide the kind of financi&acirc;&#128;&brvbar;"><meta property="article:published_time" content="2016-02-19T16:03:21+00:00"><meta property="article:modified_time" content="2016-11-04T18:56:46+00:00"><meta property="og:site_name" content="Cardinal Hayes"><meta property="og:image" content="/sites/all/themes/cardinal/img/archdiocese-table.png"><meta property="og:image:secure_url" content="https://i1.wp.com/alumni.cardinalhayes.org/wp-content/uploads/2016/02/archdiocese-table.png?ssl=1"><meta property="og:image:width" content="727"><meta property="og:image:height" content="259"><meta property="og:locale" content="en_US"><meta name="twitter:image" content="/sites/all/themes/cardinal/img/archdiocese-table.png?w=1400"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/sites/all/themes/cardinal/linked/cropped-favicon.png" sizes="32x32"><link rel="icon" href="/sites/all/themes/cardinal/linked/592738a25c1f8.png" sizes="192x192"><link rel="apple-touch-icon-precomposed" href="/sites/all/themes/cardinal/linked/592738a2b8b5d.png"><meta name="msapplication-TileImage" content="https://i2.wp.com/alumni.cardinalhayes.org/wp-content/uploads/2017/03/cropped-favicon.png?fit=270%2C270&amp;ssl=1">
<?php
print $head;
print $styles;
print $scripts;
?>
<!--[if IE 7]>
<link rel="stylesheet" href="/sites/all/themes/pgcalc_master/ie7/ie7.css">
<![endif]-->
</head>
<?php
print $page_top;
print $page;
print $page_bottom;
?>
</html>
