<body class="page-template-default page page-id-33 page-parent tribe-no-js tribe-bar-is-disabled custom-header header-image header-full-width full-width-content" original-class="page-template-default page page-id-33 page-parent tribe-no-js tribe-bar-is-disabled custom-header header-image header-full-width full-width-content" itemscope itemtype="https://schema.org/WebPage">
<div class="site-container" original-class="site-container">
<ul class="genesis-skip-link" original-class="genesis-skip-link"><li><a href="#genesis-content" class="screen-reader-shortcut" original-class="screen-reader-shortcut"> Skip to content</a></li>
<li><a href="#genesis-footer-widgets" class="screen-reader-shortcut" original-class="screen-reader-shortcut"> Skip to footer</a></li>
</ul><header class="site-header" original-class="site-header" itemscope itemtype="https://schema.org/WPHeader"><div class="wrap" original-class="wrap">
<div class="title-area" original-class="title-area">
<p class="site-title" original-class="site-title" itemprop="headline"><a href="https://catholicfoundationiowa.org/">Catholic Foundation of Southwest Iowa</a></p>
<p class="site-description" original-class="site-description" itemprop="description">Managing Gods Kingdom on Earth</p>
</div>
<nav class="nav-primary" original-class="nav-primary" aria-label="Main" itemscope itemtype="https://schema.org/SiteNavigationElement" id="genesis-nav-primary"><div class="wrap" original-class="wrap"><ul id="menu-main-navigation" class="menu genesis-nav-menu menu-primary js-superfish" original-class="menu genesis-nav-menu menu-primary js-superfish"><li id="menu-item-1093" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-1093" original-class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-1093"><a href="https://catholicfoundationiowa.org" itemprop="url"><span itemprop="name">Home</span></a></li>
<li id="menu-item-2037" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-2037" original-class="menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-2037">
<a itemprop="url"><span itemprop="name">About</span></a>
<ul class="sub-menu" original-class="sub-menu"><li id="menu-item-1113" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-33 current_page_item menu-item-1113" original-class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-33 current_page_item menu-item-1113"><a href="https://catholicfoundationiowa.org/who-are-we/" itemprop="url"><span itemprop="name">About Us</span></a></li>
 <li id="menu-item-1619" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1619" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1619"><a href="https://catholicfoundationiowa.org/who-are-we/our-staff/" itemprop="url"><span itemprop="name">Our Staff</span></a></li>
 <li id="menu-item-6073" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6073" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6073"><a href="https://catholicfoundationiowa.org/board-of-directors/" itemprop="url"><span itemprop="name">Board of Directors</span></a></li>
</ul></li>
<li id="menu-item-2039" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-2039" original-class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-2039">
<a itemprop="url"><span itemprop="name">How We Serve</span></a>
<ul class="sub-menu" original-class="sub-menu"><li id="menu-item-5913" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-5913" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-5913">
<a href="https://catholicfoundationiowa.org/donors/" itemprop="url"><span itemprop="name">Donors</span></a>
 <ul class="sub-menu" original-class="sub-menu"><li id="menu-item-1481" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1481" original-class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1481"><a href="http://plannedgiving.catholicfoundationiowa.org" itemprop="url"><span itemprop="name">Planned Giving</span></a></li>
 <li id="menu-item-1098" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1098" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1098"><a href="https://catholicfoundationiowa.org/endow-iowa/" itemprop="url"><span itemprop="name">Endow Iowa</span></a></li>
 <li id="menu-item-1108" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1108" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1108"><a href="https://catholicfoundationiowa.org/make-a-donation/donor-advised-fund/" itemprop="url"><span itemprop="name">Donor Advised Funds</span></a></li>
 <li id="menu-item-6033" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6033" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6033"><a href="https://catholicfoundationiowa.org/diocesan-funds/" itemprop="url"><span itemprop="name">Diocesan Funds</span></a></li>
 <li id="menu-item-6079" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6079" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6079"><a href="https://catholicfoundationiowa.org/parish-agency-funds/" itemprop="url"><span itemprop="name">Agency Funds</span></a></li>
 </ul></li>
 <li id="menu-item-5914" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-5914" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-5914">
<a href="https://catholicfoundationiowa.org/organizational-benefit/" itemprop="url"><span itemprop="name">Organizations</span></a>
 <ul class="sub-menu" original-class="sub-menu"><li id="menu-item-5750" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5750" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5750"><a href="https://catholicfoundationiowa.org/agency-funds/" itemprop="url"><span itemprop="name">Agency Funds</span></a></li>
 <li id="menu-item-1112" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1112" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1112"><a href="https://catholicfoundationiowa.org/grant-program/" itemprop="url"><span itemprop="name">Grant Program</span></a></li>
 </ul></li>
</ul></li>
<li id="menu-item-5690" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-5690" original-class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-5690">
<a itemprop="url"><span itemprop="name">Why We Serve</span></a>
<ul class="sub-menu" original-class="sub-menu"><li id="menu-item-2558" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2558" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2558"><a href="https://catholicfoundationiowa.org/the-joy-of-giving/" itemprop="url"><span itemprop="name">The Joy of Giving</span></a></li>
 <li id="menu-item-1620" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1620" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1620"><a href="https://catholicfoundationiowa.org/who-are-we/catholic-values-investing/" itemprop="url"><span itemprop="name">Catholic Values Investing</span></a></li>
</ul></li>
<li id="menu-item-5688" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-5688" original-class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-5688">
<a itemprop="url"><span itemprop="name">Other</span></a>
<ul class="sub-menu" original-class="sub-menu"><li id="menu-item-5811" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5811" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5811"><a href="https://catholicfoundationiowa.org/news-2/" itemprop="url"><span itemprop="name">News</span></a></li>
 <li id="menu-item-5208" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5208" original-class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5208"><a href="https://catholicfoundationiowa.org/events/" itemprop="url"><span itemprop="name">Events</span></a></li>
 <li id="menu-item-5788" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5788" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5788"><a href="https://catholicfoundationiowa.org/who-are-we/frequently-asked-questions/" itemprop="url"><span itemprop="name">FAQ</span></a></li>
 <li id="menu-item-5740" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5740" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5740"><a href="https://catholicfoundationiowa.org/employment/" itemprop="url"><span itemprop="name">Employment</span></a></li>
 <li id="menu-item-1094" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1094" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1094"><a href="https://catholicfoundationiowa.org/contact-us/" itemprop="url"><span itemprop="name">Contact Us</span></a></li>
 <li id="menu-item-4457" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4457" original-class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4457"><a target="_blank" href="https://dmf.iphiview.com/dmf/LogIn/tabid/444/Default.aspx" itemprop="url"><span itemprop="name">Login</span></a></li>
</ul></li>
<li id="menu-item-1536" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1536" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1536"><a href="https://catholicfoundationiowa.org/make-a-donation/" itemprop="url"><span itemprop="name">Make a Donation</span></a></li>
</ul></div></nav></div></header><div class="site-inner" original-class="site-inner">
<!---------------ADDING DIV FOR SIDE NAV BAR----------------------------->
<div class="rightsidebar" original-class="rightsidebar"><?php print render($page['menu']); ?></div>
<!--------------END OF ADDING DIV FOR SIDE NAV BAR------------------->
<div class="content-sidebar-wrap" original-class="content-sidebar-wrap"><main class="content" original-class="content" id="genesis-content"><article class="post-33 page type-page status-publish entry" original-class="post-33 page type-page status-publish entry" itemscope itemtype="https://schema.org/CreativeWork"><div class="entry-content" original-class="entry-content" itemprop="text"><?php require(DRUPAL_ROOT."/sites/all/themes/pgcalc_master/page.content.tpl.php"); ?></div></article></main></div></div>
<div class="footer-widgets" original-class="footer-widgets" id="genesis-footer-widgets">
<h2 class="genesis-sidebar-title screen-reader-text" original-class="genesis-sidebar-title screen-reader-text">Footer</h2>
<div class="wrap" original-class="wrap">
<div class="widget-area footer-widgets-1 footer-widget-area" original-class="widget-area footer-widgets-1 footer-widget-area">
<section id="simple-social-icons-2" class="widget simple-social-icons" original-class="widget simple-social-icons"><div class="widget-wrap" original-class="widget-wrap">
<h3 class="widgettitle widget-title" original-class="widgettitle widget-title">Follow us on Social Media</h3>
<ul class="alignleft" original-class="alignleft"><li class="ssi-facebook" original-class="ssi-facebook"><a href="https://www.facebook.com/Catholic-Foundation-of-Southwest-Iowa-518162214899000/" target="_blank" rel="noopener noreferrer"><svg role="img" class="social-facebook" original-class="social-facebook" aria-labelledby="social-facebook-2"><title id="social-facebook-2">Facebook</title><use xlink:href="https://catholicfoundationiowa.org/wp-content/plugins/simple-social-icons/symbol-defs.svg#social-facebook"></use></svg></a></li>
<li class="ssi-twitter" original-class="ssi-twitter"><a href="https://twitter.com/cfswia" target="_blank" rel="noopener noreferrer"><svg role="img" class="social-twitter" original-class="social-twitter" aria-labelledby="social-twitter-2"><title id="social-twitter-2">Twitter</title><use xlink:href="https://catholicfoundationiowa.org/wp-content/plugins/simple-social-icons/symbol-defs.svg#social-twitter"></use></svg></a></li>
</ul></div></section><section id="search-3" class="widget widget_search" original-class="widget widget_search"><div class="widget-wrap" original-class="widget-wrap"><form class="search-form" original-class="search-form" itemprop="potentialAction" itemscope itemtype="https://schema.org/SearchAction" method="get" action="https://catholicfoundationiowa.org/" role="search">
<meta itemprop="target" content="https://catholicfoundationiowa.org/?s={s}"><label class="search-form-label screen-reader-text" original-class="search-form-label screen-reader-text" for="searchform-5be0a8825cf709.67380106">Search this website</label><input itemprop="query-input" type="search" name="s" id="searchform-5be0a8825cf709.67380106" placeholder="Search this website &hellip;"><input type="submit" value="Search"></form></div></section></div>
<div class="widget-area footer-widgets-2 footer-widget-area" original-class="widget-area footer-widgets-2 footer-widget-area"><section id="email-subscribers-3" class="widget widget_text elp-widget" original-class="widget widget_text elp-widget"><!---------------------------REMOVING SUBSCRIBE FORM----------------<div class="widget-wrap" original-class="widget-wrap">
<h3 class="widgettitle widget-title" original-class="widgettitle widget-title">Subscribe Online</h3>
 <div class="es_form_container" original-class="es_form_container">
 <form class="es_widget_form" original-class="es_widget_form" data-es_form_id="es_widget_form">
 <div class="es_caption" original-class="es_caption">Receive updates from the Catholic Foundation in your Email</div>
 <div class="es_lablebox" original-class="es_lablebox">
 <label class="es_widget_form_name" original-class="es_widget_form_name">Name</label>
 </div>
 <div class="es_textbox" original-class="es_textbox">
 <input type="text" id="es_txt_name" class="es_textbox_class" original-class="es_textbox_class" name="es_txt_name" value="" maxlength="60">
</div>
 <div class="es_lablebox" original-class="es_lablebox">
 <label class="es_widget_form_email" original-class="es_widget_form_email">Email *</label>
 </div>
 <div class="es_textbox" original-class="es_textbox">
 <input type="email" id="es_txt_email" class="es_textbox_class" original-class="es_textbox_class" name="es_txt_email" value="" maxlength="60" required>
</div>
 <div class="es_button" original-class="es_button">
 <input type="submit" id="es_txt_button" class="es_textbox_button es_submit_button" original-class="es_textbox_button es_submit_button" name="es_txt_button" value="Subscribe">
</div>
 <div class="es_msg" original-class="es_msg" id="es_widget_msg">
 <span id="es_msg"></span>
 </div>
 <div style="position:absolute; left: -5000px"><input type="text" name="es_required_field" class="es_required_field" original-class="es_required_field" tabindex="-1" autocomplete="es_test"></div>
 <input type="hidden" id="es_txt_group" name="es_txt_group" value="Public"><input type="hidden" name="es-subscribe" id="es-subscribe" value="cde3bdebc6">
</form>
 </div>
 </div>---------------------------------------------END OF REMOVING SUBSCRIBE FORM--------------------------></section></div>
<div class="widget-area footer-widgets-3 footer-widget-area" original-class="widget-area footer-widgets-3 footer-widget-area"><section id="text-17" class="widget widget_text" original-class="widget widget_text"><div class="widget-wrap" original-class="widget-wrap">
<h3 class="widgettitle widget-title" original-class="widgettitle widget-title">Contact Information</h3>
 <div class="textwidget" original-class="textwidget">
<p>Catholic Foundation of Southwest Iowa<br>
601 Grand Ave<br>
Des Moines, IA 501309</p>
<p>Phone: (515) 237-5044<br>
Fax: (515) 237-5042</p>
</div>
 </div></section></div>
</div>
</div>
<footer class="site-footer" original-class="site-footer" itemscope itemtype="https://schema.org/WPFooter"><div class="wrap" original-class="wrap"><font size="3" color="#fff">Copyright &copy;&nbsp;<?php print variable_get('pgc_copyright_year'); ?> The Catholic Foundation of Southwest Iowa - 601 Grand Ave - Des Moines, IA 50309</font></div></footer></div>
<script type="text/javascript">jQuery( document ).ready(function() { jQuery( ".testimonials-list" ).lightSlider( {auto: true, controls: true,item: 2, mode: 'fade', pauseOnHover: true, loop: true,pause: 6000,responsive : [ { breakpoint:1023, settings: { item:2 } }, { breakpoint:860, settings: { item:1 } }]} );} );</script><script>
 ( function ( body ) {
 'use strict';
 body.className = body.className.replace( /\btribe-no-js\b/, 'tribe-js' );
 } )( document.body );
 </script><style type="text/css" media="screen"> #simple-social-icons-2 ul li a, #simple-social-icons-2 ul li a:hover, #simple-social-icons-2 ul li a:focus { background-color: #ffffff !important; border-radius: 14px; color: #5d2685 !important; border: 0px #ffffff solid !important; font-size: 25px; padding: 13px; } #simple-social-icons-2 ul li a:hover, #simple-social-icons-2 ul li a:focus { background-color: #bcbebd !important; border-color: #ffffff !important; color: #5d2685 !important; } #simple-social-icons-2 ul li a:focus { outline: 1px dotted #bcbebd !important; }</style><script> /* <![CDATA[ */var tribe_l10n_datatables = {"aria":{"sort_ascending":": activate to sort column ascending","sort_descending":": activate to sort column descending"},"length_menu":"Show _MENU_ entries","empty_table":"No data available in table","info":"Showing _START_ to _END_ of _TOTAL_ entries","info_empty":"Showing 0 to 0 of 0 entries","info_filtered":"(filtered from _MAX_ total entries)","zero_records":"No matching records found","search":"Search:","all_selected_text":"All items on this page were selected. ","select_all_link":"Select all pages","clear_selection":"Clear Selection.","pagination":{"all":"All","next":"Next","previous":"Previous"},"select":{"rows":{"0":"","_":": Selected %d rows","1":": Selected 1 row"}},"datepicker":{"dayNames":["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],"dayNamesShort":["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],"dayNamesMin":["S","M","T","W","T","F","S"],"monthNames":["January","February","March","April","May","June","July","August","September","October","November","December"],"monthNamesShort":["January","February","March","April","May","June","July","August","September","October","November","December"],"nextText":"Next","prevText":"Prev","currentText":"Today","closeText":"Done"}};var tribe_system_info = {"sysinfo_optin_nonce":"6a1ad41904","clipboard_btn_text":"Copy to clipboard","clipboard_copied_text":"System info copied","clipboard_fail_text":"Press \"Cmd + C\" to copy"};/* ]]> */ </script><link rel="stylesheet" id="soliloquy-style-css-css" href="/sites/all/themes/catholiciowa2/css/soliloquy.css" type="text/css" media="all"><script type="text/javascript">
/* <![CDATA[ */
var wpcf7 = {"apiSettings":{"root":"https:\/\/catholicfoundationiowa.org\/wp-json\/contact-form-7\/v1","namespace":"contact-form-7\/v1"},"recaptcha":{"messages":{"empty":"Please verify that you are not a robot."}}};
/* ]]> */
</script><script type="text/javascript" src="/sites/all/themes/catholiciowa2/js/scripts.js"></script><script type="text/javascript">
/* <![CDATA[ */
var es_widget_page_notices = {"es_email_notice":"Please enter email address","es_success_message":"Successfully Subscribed.","es_success_notice":"Your subscription was successful! Kindly check your mailbox and confirm your subscription. If you don't see the email within a few minutes, check the spam\/junk folder.","es_email_exists":"Email Address already exists!","es_error":"Oops.. Unexpected error occurred.","es_invalid_email":"Invalid email address","es_try_later":"Please try after some time","es_ajax_url":"https:\/\/catholicfoundationiowa.org\/wp-admin\/admin-ajax.php"};
/* ]]> */
</script><script type="text/javascript" src="/sites/all/themes/catholiciowa2/js/es-widget-page.js"></script><script type="text/javascript" src="/sites/all/themes/catholiciowa2/js/checkout.js"></script><script type="text/javascript" src="/sites/all/themes/catholiciowa2/js/jquery.validate.min.js"></script><script type="text/javascript" src="/sites/all/themes/catholiciowa2/js/accounting.min.js"></script><script type="text/javascript">
/* <![CDATA[ */
var spGeneral = {"strings":{"currency":"USD","currencySymbol":"$","currencyPosition":"left","decimalSeparator":".","thousandSeparator":",","ajaxurl":"https:\/\/catholicfoundationiowa.org\/wp-admin\/admin-ajax.php"},"booleans":{"isZeroDecimal":false,"scriptDebug":false},"i18n":{"mediaTitle":"Insert Media","mediaButtonText":"Use Image","limitPaymentButtonField":"You may only add one Payment Button field per form.","limitCustomAmountField":"You may only add one Custom Amount Field per form.","limitPlanSelectField":"You may only add one Subscription Plan Select field per form.","limitCouponField":"You may only add one Coupon field per form.","limitRecurringAmountToggleField":"You may only add one Recurring Amount Toggle field per form","limitMaxFields":"The maximum number of fields is 20.","couponPercentOffText":"% off","couponAmountOffText":"off"},"integers":{"decimalPlaces":2,"minAmount":1}};
/* ]]> */
</script><script type="text/javascript" src="/sites/all/themes/catholiciowa2/js/shared.min.js"></script><script type="text/javascript">
/* <![CDATA[ */
var simplePayForms = [];
/* ]]> */
</script><script type="text/javascript" src="/sites/all/themes/catholiciowa2/js/public.min.js"></script><script type="text/javascript" src="/sites/all/themes/catholiciowa2/js/core.min.js"></script><script type="text/javascript" src="/sites/all/themes/catholiciowa2/js/datepicker.min.js"></script><script type="text/javascript">
jQuery(document).ready(function(jQuery){jQuery.datepicker.setDefaults({"closeText":"Close","currentText":"Today","monthNames":["January","February","March","April","May","June","July","August","September","October","November","December"],"monthNamesShort":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"nextText":"Next","prevText":"Previous","dayNames":["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],"dayNamesShort":["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],"dayNamesMin":["S","M","T","W","T","F","S"],"dateFormat":"MM d, yy","firstDay":0,"isRTL":false});});
</script><script type="text/javascript" src="/sites/all/themes/catholiciowa2/js/public-pro.min.js"></script><script type="text/javascript" src="/sites/all/themes/catholiciowa2/js/blankshield.min.js"></script><script type="text/javascript" src="/sites/all/themes/catholiciowa2/js/block-tabnapping.js"></script><script type="text/javascript" src="/sites/all/themes/catholiciowa2/js/hoverIntent.min.js"></script><script type="text/javascript" src="/sites/all/themes/catholiciowa2/js/superfish.min.js"></script><script type="text/javascript" src="/sites/all/themes/catholiciowa2/js/superfish.args.min.js"></script><script type="text/javascript" src="/sites/all/themes/catholiciowa2/js/skip-links.min.js"></script><script type="text/javascript" src="/sites/all/themes/catholiciowa2/js/match-height.js"></script><script type="text/javascript" src="/sites/all/themes/catholiciowa2/js/global.js"></script><script type="text/javascript">
/* <![CDATA[ */
var genesis_responsive_menu = {"mainMenu":"Menu","menuIconClass":"ionicons-before ion-ios-drag","subMenu":"Submenu","subMenuIconClass":"ionicons-before ion-chevron-down","menuClasses":{"others":[".nav-primary"]}};
/* ]]> */
</script><script type="text/javascript" src="/sites/all/themes/catholiciowa2/js/responsive-menus.min.js"></script><script type="text/javascript" src="/sites/all/themes/catholiciowa2/js/wp-embed.min.js"></script><script type="text/javascript">
/* <![CDATA[ */
var soliloquy_ajax = {"ajax":"https:\/\/catholicfoundationiowa.org\/wp-admin\/admin-ajax.php","ajax_nonce":"c61c138c2f"};
/* ]]> */
</script><script type="text/javascript" src="/sites/all/themes/catholiciowa2/js/soliloquy-min.js"></script><script type="text/javascript">
 if ( typeof soliloquy_slider === 'undefined' || false === soliloquy_slider ) {soliloquy_slider = {};}var soliloquy_width_1830 = jQuery('#soliloquy-container-1830').width() < 900 ? 900 : jQuery('#soliloquy-container-1830').width();jQuery('#soliloquy-container-1830').css('height', Math.round(soliloquy_width_1830/(900/360))).fadeTo(300, 1);jQuery(document).ready(function($){var soliloquy_container_1830 = $('#soliloquy-container-1830'),soliloquy_1830 = $('#soliloquy-1830'),soliloquy_holder_1830 = $('#soliloquy-1830').find('.soliloquy-preload');if ( 0 !== soliloquy_holder_1830.length ) {var soliloquy_src_attr = 'data-soliloquy-src';soliloquy_holder_1830.each(function() {var soliloquy_src = $(this).attr(soliloquy_src_attr);if ( typeof soliloquy_src === 'undefined' || false === soliloquy_src ) {return;}var soliloquy_image = new Image();soliloquy_image.src = soliloquy_src;$(this).attr('src', soliloquy_src).removeAttr(soliloquy_src_attr);});}soliloquy_slider['1830'] = soliloquy_1830.soliloquy({slideSelector: '.soliloquy-item',speed: 400,pause: 5000,auto: 1,keyboard: 1,useCSS: 1,startSlide: 0,autoHover: 0,autoDelay: 0,adaptiveHeight: 1,adaptiveHeightSpeed: 400,infiniteLoop: 1,mode: 'fade',pager: 0,controls: 1,autoControls: 0,autoControlsCombine: 0,nextText: '',prevText: '',startText: '',stopText: '',onSliderLoad: function(currentIndex){soliloquy_container_1830.find('.soliloquy-active-slide').removeClass('soliloquy-active-slide').attr('aria-hidden','true');soliloquy_container_1830.css({'height':'auto','background-image':'none'});if ( soliloquy_container_1830.find('.soliloquy-slider li').length > 1 ) {soliloquy_container_1830.find('.soliloquy-controls').fadeTo(300, 1);} else {soliloquy_container_1830.find('.soliloquy-controls').addClass('soliloquy-hide');}soliloquy_1830.find('.soliloquy-item:not(.soliloquy-clone):eq(' + currentIndex + ')').addClass('soliloquy-active-slide').attr('aria-hidden','false');$('.soliloquy-clone .soliloquy-video-holder').remove();soliloquy_container_1830.find('.soliloquy-controls-direction').attr('aria-label','carousel buttons').attr('aria-controls', 'soliloquy-container-1830');soliloquy_container_1830.find('.soliloquy-controls-direction a.soliloquy-prev').attr('aria-label','previous');soliloquy_container_1830.find('.soliloquy-controls-direction a.soliloquy-next').attr('aria-label','next');$(window).trigger('resize');soliloquy_container_1830.parent().attr('data-soliloquy-loaded', 1);},onSlideBefore: function(element, oldIndex, newIndex, oldelm ){soliloquy_container_1830.find('.soliloquy-active-slide').removeClass('soliloquy-active-slide').attr('aria-hidden','true');$(element).addClass('soliloquy-active-slide').attr('aria-hidden','false');},onSlideAfter: function(element, oldIndex, newIndex){}});}); </script></body>