<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" original-class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]--><!--[if IE 7]> <html class="no-js lt-ie9 lt-ie8" original-class="no-js lt-ie9 lt-ie8"> <![endif]--><!--[if IE 8]> <html class="no-js lt-ie9" original-class="no-js lt-ie9"> <![endif]--><!--[if gt IE 8]><!--><html class="no-js" original-class="no-js"><!--<![endif]--><!-- CLOUDWAYS --><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title><?php print $head_title; ?></title><meta name="keywords" content="TMF, Texas Methodist Foundation, legacy giving, support ministries"><meta name="description" content="Support TMF ministries through legacy giving"><link rel="canonical" href="https://www.tmf-fdn.org/legacy-giving/support-tmf-ministries/"><!-- generated by seo_lite --><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="author" content="Texas Methodist Foundation"><!-- Facebook OG --><meta property="og:locale" content="en_US"><meta property="og:site_name" content="TMF, Inc."><meta property="og:url" content="https://www.tmf-fdn.org/legacy-giving/support-tmf-ministries"><!-- channel:default_page --><meta property="og:type" content="article"><meta property="og:title" content="Support TMF Ministries"><meta name="p:domain_verify" content="323b385dee3cb5c42953603f7454f090"><!-- <meta name="google-site-verification" content="" /> --><link rel="shortcut icon" href="https://www.tmf-fdn.org/favicon.ico" type="image/x-icon"><link rel="icon" href="https://www.tmf-fdn.org/favicon.ico" type="image/x-icon"><script src="/sites/all/themes/texas_methodist/js/nog2wbj.js"></script><script>try{Typekit.load();}catch(e){}</script><link rel="stylesheet" href="/sites/all/themes/texas_methodist/css/master.css"><script src="/sites/all/themes/texas_methodist/js/modernizr.js"></script><script src="/sites/all/themes/texas_methodist/js/lunametrics-youtube.gtm.min.js"></script><!-- Facebook Pixel Code: inserted July 18, 2017 --><script>
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window,document,'script',#Html0064
'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '139589506624272');
fbq('track', 'PageView');
</script><noscript>
<img height="1" width="1" src="https://www.facebook.com/tr?id=139589506624272&amp;ev=PageView%0A&amp;noscript=1"></noscript><!-- End Facebook Pixel Code --><!-- Twitter universal website tag code --><script>
!function(e,t,n,s,u,a){e.twq||(s=e.twq=function(){s.exe?s.exe.apply(s,arguments):s.queue.push(arguments);},s.version='1.1',s.queue=[],u=t.createElement(n),u.async=!0,u.src='//static.ads-twitter.com/uwt.js',
a=t.getElementsByTagName(n)[0],a.parentNode.insertBefore(u,a))}(window,document,'script');
// Insert Twitter Pixel ID and Standard Event data below
twq('init','nxoxd');
twq('track','PageView');
</script><!-- End Twitter universal website tag code --><meta name="p:domain_verify" content="323b385dee3cb5c42953603f7454f090"><!-- DO NOT MODIFY -->
<?php
print $head;
print $styles;
print $scripts;
?>
<!--[if IE 7]>
<link rel="stylesheet" href="/sites/all/themes/pgcalc_master/ie7/ie7.css">
<![endif]-->
</head>
<?php
print $page_top;
print $page;
print $page_bottom;
?>
</html>
