/*
 Copyright 2013 Blue State Digital, Inc.
 Blue State Digital Google Analytics Integration Library

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var _gaq=_gaq||[],optimizely=optimizely||[];_gaq.push(["_setSiteSpeedSampleRate",10],["_setAllowAnchor",!0],["_setAllowLinker",!0]);
(function(c){function n(b){var a=document.createElement("a");a.href=b;return a}function o(b){return b.charAt(0).toUpperCase()+b.slice(1).toLowerCase()}function l(b){return b&&n(b).pathname.replace(/(^\/?)/,"/")}function g(b){return(RegExp("(?:^|; )"+b+"=([^;]*)").exec(document.cookie)||[]).pop()}function i(b,a,d){ga_integration_config.nocookie||(d=d?"; expires="+(new Date(864E5*d+(new Date).getTime())).toGMTString():"",document.cookie=b+"="+a+d+"; path=/; domain="+ga_integration_config.cookiedomain)}
function m(b,a,d,e,c){f.event(b,a,e,c);f.social(b,a,d,e)}function p(b){var a=1,d=0,c;if(b){a=0;for(c=b.length-1;0<=c;c--)d=b.charCodeAt(c),a=(a<<6&268435455)+d+(d<<14),d=a&266338304,a=0!=d?a^d>>21:a}return a}function q(b){return b.match(/contribution/i)&&c("form#contribution").length?(b=Math.round(!c("#amt_other:checked").length?c('input[name="amount"]:checked').val():c('input[name="amount_other"]').val()),b!=b||1E9<Math.abs(b)?0:b):0}function r(b){ga_integration_config.data.action=b;var a=b.modulename;
if(a){i("_bsda_s",1,180);var d=b.formname,e=b.transaction_amt;if(b.savedPaymentInfo)a="Quick Donate Opt-In",i("_bsda_q",1,180);else if(e){i("_bsda_c",Math.round(e),180);var h=b.contribution_key,k=-1!==c.inArray(e,b.pageamounts)?Math.round(e):"other",k=b.contribution_page_id+"_"+k,s=+b.pagetype,g=+b.is_recurring?"BSD Recurring":"BSD";b.used_quick_donate&&(g+=" Quick Donate",k+="_QD",i("_bsda_q",1,180));f.ecommerce(h,e,k,d,g+(4===s?" Memberships":2===s?" Tickets":3===s?" Custom Contributions":" Contributions"));
optimizely.push(["trackEvent","bsdtracker",100*e])}f.event("Completions",a,d,Math.ceil(e||0));optimizely.push(["trackEvent","bsdtracker_"+a])}}window.ga_integration_config=window.ga_integration_config||{};var f={event:function(b){var a;a=1===arguments.length?b:Array.prototype.slice.call(arguments,0);window._gaq&&_gaq.push(["_trackEvent"].concat(a));if("function"===typeof ga)try{a[4]&&!0===a[4]&&(a[4]={nonInteraction:1}),ga.apply(this,["send","event"].concat(a))}catch(d){}},social:function(){var b=
Array.prototype.slice.call(arguments,0);window._gaq&&_gaq.push(["_trackSocial"].concat(b));if("function"===typeof ga)try{ga.apply(this,["send","social"].concat(b))}catch(a){}},custom:function(){var b=Array.prototype.slice.call(arguments,0);window._gaq&&_gaq.push(["_setCustomVar"].concat(b).concat(2));if("function"===typeof ga)try{"false"!==b[2]&&ga.apply(this,["set","dimension"+b[0],b[1]+b[2]])}catch(a){}},ecommerce:function(b,a,d,c,h){window._gaq&&_gaq.push(["_addTrans",b,"",a,"0","0","","",""],
["_addItem",b,d,c,h,a,"1"],["_trackTrans"]);if("function"===typeof ga)try{ga("require","ecommerce","ecommerce.js"),ga("ecommerce:addTransaction",{id:b,affiliation:"",revenue:a,shipping:"0",tax:"0"}),ga("ecommerce:addItem",{id:b,name:c,sku:d,category:h,price:a,quantity:"1"}),ga("ecommerce:send")}catch(f){}},queue:function(b){window._gaq&&_gaq.push(b);if("function"===typeof ga)try{ga(b)}catch(a){}}};if(!ga_integration_config.cookiedomain){var t=location.hostname.match(/\.uk$/)?-3:-2;ga_integration_config.cookiedomain=
location.hostname.split(".").slice(t).join(".")}var u=window.onerror;window.onerror=function(b,a,c){u&&u.apply(this,arguments);f.event("JavaScript Errors",b,a+"_"+c,0,!0)};var j=function(){var b={};location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi,function(a,c,e){b[c]=e});return b}();j.source&&f.custom(1,"Source",j.source);j.subsource&&f.custom(5,"Subsource",j.subsource);g("msid")&&(t=ga_integration_config.msid_seed?""+(parseInt(g("msid"),16)^ga_integration_config.msid_seed):g("msid"),f.custom(2,"msid",
t));f.custom(3,"Has GUID",""+!!g("guid"));f.custom(4,"Has Spud",""+!!g("spud"));if(!c||!c.fn)throw Error("No jQuery found.");c.fn.analytics=function(b,a,d){if(!b)return this.trigger(a||"mousedown");var e=a?a+".analytics":"keydown.analytics mousedown.analytics",h=d||"one",k=function(d){if(a||d.type==="mousedown"||d.which===13)typeof b==="function"?b.apply(this):c.isArray(b)&&b[1]&&typeof b[1]!=="number"?f.event(b):(typeof b==="string"||c.isArray(b))&&optimizely.push(["trackEvent"].concat(b))};return d&&
!c.fn.live?c(document).delegate(this.selector,e,k):this[h](e,k)};c.fn.registerBSDError=function(b){this.length&&f.event("Error",b,l(document.referrer),q(b),true)};p(location.hostname)%7===(new Date).getDay()&&1===Math.ceil(100*Math.random())&&!g("__bsdzh")&&((new Image).src="//bsd-analytics.appspot.com/?"+c.param({hostname:location.hostname,src:c("script:last").attr("src"),jQ:c.fn.jquery}));ga_integration_config.util={createCookie:i,readCookie:g,getURLParam:j,hash:p,contrib_amt:q,bsdtracker_to_ga:r,
getPathname:l,social_event:m,proper:o};ga_integration_config.data={};c(document).ready(function(){function b(a){if(a.type==="mousedown"||a.which===13){$this=c(this);$this.unbind("keydown mousedown",b);a=$this.is("form")?$this:$this.closest("form");a=a.attr("id")||a.attr("name")||a.attr("action")||"(none)";f.event("Form Submits",a,location.pathname,q(a))}}c("input").filter('[type="image"],[type="submit"]').bind("mousedown",b);c("form").bind("keydown",b);c("span.signuperror").registerBSDError("Signup");
c("div.contriberrorbanner").registerBSDError("Contribution");c("#invitationpage .error").registerBSDError("Share");c("[href^='http'], [href^='//']").analytics(function(){if(this.hostname!==location.hostname){var a=/(facebook|twitter|addthis|youtube|pinterest)(\.com)/i.exec(this.href);if(a){var b=this.href.match(/facebook\.com\/sharer.php/)?decodeURIComponent(this.href.replace("http://www.facebook.com/sharer.php?u=","")):this.href;m(o(a[1]),"click",b,l(b))}else f.event("Exits",n(this.href).hostname,
this.href)}},null,"live");c("a").analytics(function(){var a=this.pathname.match(/\.[0-9a-z]{2,4}$/i),b=ga_integration_config.file_extensions||".pdf";a&&a[0].match(b)&&!a[0].match(/(.htm*|.php|.asp*|.cfm)$/)?f.event("File Clicks",c(this).text(),this.href,0,true):this.protocol==="mailto:"&&f.event("Mailto: Clicks",c(this).text(),this.href,0,true)},null,"live");c("video,audio").bind("play ended pause",function(a){f.event(o(this.nodeName),o(a.type),this.src,0,true)});c.fn._link=c.fn._link||function(a,
b){var e=b||location.hostname.split(".").slice(-2).join(".");this.one("click",function(){if(~c.inArray(e,a)&&e!=this.hostname.split(".").slice(-2).join(".")){$this=c(this);ga.queue(function(){$this.attr("href",function(a,b){return _gat._getTrackerByName()._getLinkerUrl(b,true)})})}})};window.BSDTracker?r(BSDTracker[BSDTracker.signup?"signup":BSDTracker.contribution?"contribution":""].jsonData):j.td&&c.getJSON((ga_integration_config.bsddomain?ga_integration_config.bsddomain:"//www.bluestatedigital.com")+
"/page/tracking/action-decode?td="+j.td+"&callback=?",function(a){r(a)});window.bQuery&&bQuery.fn.mailcheck&&c("#email").blur(function(){var a=c(".bsd-mailcheck");if(a.length){var b=a.text();f.event("Mailcheck","Shown",b,0,true);a=function(){f.event("Mailcheck","Clicked",b,0,true)};c.fn.live?c(".bsd-mailcheck a").live("click",a):c("#signup").delegate(".bsd-mailcheck a","click",a)}});c(window).load(function(){optimizely.variationNamesMap&&c.each(optimizely.variationNamesMap,function(a,b){f.event("Optimizely",
optimizely.allExperiments[a].name,b,0,true)});if(ga_integration_config.nocookie!==false&&ga_integration_config.nospud!==false&&ga_integration_config.noloe!==false&&g("guid")&&!g("loega")&&(ga_integration_config.bsddomain||location.pathname.match(/^\/page\//)))c.getJSON((ga_integration_config.bsddomain||"")+"/page/graph/loe/"+g("guid")+"?callback=?",function(a){var b=[],c="",h=0;ga_integration_config.data.loe=a;for(var g in a)a[g]&&typeof a[g]==="boolean"&&b.push(g);b=b.length?b.sort().join("-"):"Anonymous";
if(a.donor){h=Math.ceil(a.highest_previous_contribution);c=""+h;i("_bsda_c",h,180)}a.email&&i("_bsda_s",1,180);a.qd_enrolled&&i("_bsda_q",1,180);f.event("Ladder of Engagement",b,c,h,true);i("loega",1)});(function(){if(ga_integration_config.nocookie!==true){var a=g("__utmz")||"";if(!j.source&&!g("source")||a&&p(a).toString()!==g("__bsdzh")){var b,e;e=a.split(".").slice(4).join(".").split("|");var h={};c.each(e,function(b,a){var c=a.split("=");c[1]&&!c[1].match(/^\(.*\)$/)&&(h[c[0]]=decodeURIComponent(c[1]))});
if(h.utmgclid){b="cpc_google";e=h.utmctr}else{var f=[];c.each(h,function(a,b){a!=="utmcmd"&&a!=="utmcsr"&&a!=="utmcct"&&f.push(b)});h.utmcmd&&h.utmcsr&&(b=h.utmcmd+"_"+h.utmcsr);e=f.sort().join("_")}if(j.source||b)i("source",j.source||b,7);if(j.subsource||e)i("subsource",j.subsource||e,7);i("__bsdzh",p(a))}}})();if(window.FB&&FB.Event){FB.Event.subscribe("edge.create",function(a){m("Facebook","Like",a,l(a),1)});FB.Event.subscribe("edge.remove",function(a){m("Facebook","Unlike",a,l(a),-1)});FB.Event.subscribe("comment.create",
function(a){m("Facebook","Comment",a.href,l(a.href),1)});FB.Event.subscribe("comment.remove",function(a){m("Facebook","Uncomment",a.href,l(a.href),-1)})}window.twttr&&twttr.events&&twttr.ready&&twttr.ready(function(a){"click tweet retweet follow favorite".replace(/\w+/g,function(b){a.events.bind(b,function(a){var b;a&&a.target&&(a.target.src?b=n(decodeURIComponent((a.target.src.match(/[&#?](url=)([^&]*)/)||[""]).pop())):a&&a.target&&a.target.href&&c.each(decodeURIComponent(a.target.search).replace(/\+/g,
" ").split(/&| |\=/g),function(a,c){if(c.match(/(^https?:\/\/)|(^www.)/)){b=n(c);return false}}));b&&m("Twitter",a.type,b.href.replace(b.hash,""),b.pathname)})})})})})})(window.jQuery||window.bQuery);
