<!DOCTYPE html>
<html lang="en-US" xmlns:fb="https://www.facebook.com/2008/fbml" xmlns:addthis="https://www.addthis.com/help/api-spec" class="no-js" original-class="no-js"><head><!-- Google Tag Manager --><script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
 new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
 j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
 })(window,document,'script','dataLayer','GTM-N58MN5');</script><!-- End Google Tag Manager --><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="profile" href="/sites/all/themes/salesianmissions2/linked/11"><link rel="pingback" href="https://salesianmissions.org/xmlrpc.php"><title><?php print $head_title; ?></title><meta name="robots" content="noindex,follow"><link rel="dns-prefetch" href="//s7.addthis.com"><link rel="dns-prefetch" href="//fonts.googleapis.com"><link rel="dns-prefetch" href="//s.w.org"><link rel="alternate" type="application/rss+xml" title="Salesian Mission &raquo; Feed" href="/sites/all/themes/salesianmissions2/linked/feed"><link rel="alternate" type="application/rss+xml" title="Salesian Mission &raquo; Comments Feed" href="/sites/all/themes/salesianmissions2/linked/5bbcdb98bc865"><script type="text/javascript">
 window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/11\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/11\/svg\/","svgExt":".svg","source":{"concatemoji":"https:\/\/salesianmissions.org\/wp-includes\/js\/wp-emoji-release.min.js?ver=4.9.8"}};
 !function(a,b,c){function d(a,b){var c=String.fromCharCode;l.clearRect(0,0,k.width,k.height),l.fillText(c.apply(this,a),0,0);var d=k.toDataURL();l.clearRect(0,0,k.width,k.height),l.fillText(c.apply(this,b),0,0);var e=k.toDataURL();return d===e}function e(a){var b;if(!l||!l.fillText)return!1;switch(l.textBaseline="top",l.font="600 32px Arial",a){case"flag":return!(b=d([55356,56826,55356,56819],[55356,56826,8203,55356,56819]))&&(b=d([55356,57332,56128,56423,56128,56418,56128,56421,56128,56430,56128,56423,56128,56447],[55356,57332,8203,56128,56423,8203,56128,56418,8203,56128,56421,8203,56128,56430,8203,56128,56423,8203,56128,56447]),!b);case"emoji":return b=d([55358,56760,9792,65039],[55358,56760,8203,9792,65039]),!b}return!1}function f(a){var c=b.createElement("script");c.src=a,c.defer=c.type="text/javascript",b.getElementsByTagName("head")[0].appendChild(c)}var g,h,i,j,k=b.createElement("canvas"),l=k.getContext&&k.getContext("2d");for(j=Array("flag","emoji"),c.supports={everything:!0,everythingExceptFlag:!0},i=0;i<j.length;i++)c.supports[j[i]]=e(j[i]),c.supports.everything=c.supports.everything&&c.supports[j[i]],"flag"!==j[i]&&(c.supports.everythingExceptFlag=c.supports.everythingExceptFlag&&c.supports[j[i]]);c.supports.everythingExceptFlag=c.supports.everythingExceptFlag&&!c.supports.flag,c.DOMReady=!1,c.readyCallback=function(){c.DOMReady=!0},c.supports.everything||(h=function(){c.readyCallback()},b.addEventListener?(b.addEventListener("DOMContentLoaded",h,!1),a.addEventListener("load",h,!1)):(a.attachEvent("onload",h),b.attachEvent("onreadystatechange",function(){"complete"===b.readyState&&c.readyCallback()})),g=c.source||{},g.concatemoji?f(g.concatemoji):g.wpemoji&&g.twemoji&&(f(g.twemoji),f(g.wpemoji)))}(window,document,window._wpemojiSettings);
 </script><style type="text/css">
img.wp-smiley,
img.emoji {
 display: inline !important;
 border: none !important;
 box-shadow: none !important;
 height: 1em !important;
 width: 1em !important;
 margin: 0 .07em !important;
 vertical-align: -0.1em !important;
 background: none !important;
 padding: 0 !important;
}
</style><link rel="stylesheet" id="megamenu-css" href="/sites/all/themes/salesianmissions2/css/style.css" type="text/css" media="all"><link rel="stylesheet" id="dashicons-css" href="/sites/all/themes/salesianmissions2/css/dashicons.min.css" type="text/css" media="all"><link rel="stylesheet" id="search-filter-plugin-styles-css" href="/sites/all/themes/salesianmissions2/css/search-filter.min.css" type="text/css" media="all"><link rel="stylesheet" id="llorix-one-lite-font-css" href="/sites/all/themes/salesianmissions2/css/css" type="text/css" media="all"><link rel="stylesheet" id="llorix-one-lite-fontawesome-css" href="/sites/all/themes/salesianmissions2/css/font-awesome.min.css" type="text/css" media="all"><link rel="stylesheet" id="llorix-one-lite-bootstrap-style-css" href="/sites/all/themes/salesianmissions2/css/bootstrap.min.css" type="text/css" media="all"><link rel="stylesheet" id="llorix-one-lite-owl-style-css" href="/sites/all/themes/salesianmissions2/css/owl.carousel.min.css" type="text/css" media="all"><link rel="stylesheet" id="llorix-one-lite-owl-theme-style-css" href="/sites/all/themes/salesianmissions2/css/owl.theme.default.min.css" type="text/css" media="all"><link rel="stylesheet" id="llorix-one-lite-style-css" href="/sites/all/themes/salesianmissions2/css/5bbcdb6f58cad.css" type="text/css" media="all"><style id="llorix-one-lite-style-inline-css" type="text/css">
.overlay-layer-wrap{ background:rgba(13, 60, 85, 0.5);}
</style><link rel="stylesheet" id="llorix-one-lite-slick-css-css" href="/sites/all/themes/salesianmissions2/css/slick.css" type="text/css" media="all"><link rel="stylesheet" id="llorix-one-lite-slick-theme-css-css" href="/sites/all/themes/salesianmissions2/css/slick-theme.css" type="text/css" media="all"><link rel="stylesheet" id="toolset-select2-css-css" href="/sites/all/themes/salesianmissions2/css/select2.css" type="text/css" media="screen"><link rel="stylesheet" id="tablepress-default-css" href="/sites/all/themes/salesianmissions2/css/tablepress-combined.min.css" type="text/css" media="all"><link rel="stylesheet" id="js_composer_front-css" href="/sites/all/themes/salesianmissions2/css/js_composer.min.css" type="text/css" media="all"><link rel="stylesheet" id="js_composer_custom_css-css" href="/sites/all/themes/salesianmissions2/css/custom.css" type="text/css" media="all"><link rel="stylesheet" id="addthis_all_pages-css" href="/sites/all/themes/salesianmissions2/css/addthis_wordpress_public.min.css" type="text/css" media="all"><script type="text/javascript" src="/sites/all/themes/salesianmissions2/js/jquery.js"></script><script type="text/javascript" src="/sites/all/themes/salesianmissions2/js/jquery-migrate.min.js"></script><script type="text/javascript">
/* <![CDATA[ */
var SF_LDATA = {"ajax_url":"https:\/\/salesianmissions.org\/wp-admin\/admin-ajax.php","home_url":"https:\/\/salesianmissions.org\/"};
/* ]]> */
</script><script type="text/javascript" src="/sites/all/themes/salesianmissions2/js/search-filter-build.min.js"></script><script type="text/javascript" src="/sites/all/themes/salesianmissions2/js/chosen.jquery.min.js"></script><script type="text/javascript" src="/sites/all/themes/salesianmissions2/js/knockout-3.4.0.js"></script><script type="text/javascript" src="/sites/all/themes/salesianmissions2/js/masonry.pkgd.min.js"></script><link rel="https://api.w.org/" href="/sites/all/themes/salesianmissions2/linked/wp-json"><link rel="EditURI" type="application/rsd+xml" title="RSD" href="/sites/all/themes/salesianmissions2/linked/xmlrpc.php"><link rel="wlwmanifest" type="application/wlwmanifest+xml" href="/sites/all/themes/salesianmissions2/linked/wlwmanifest.xml"><link rel="canonical" href="https://salesianmissions.org/about-us/news-publications/salesian-magazine/"><link rel="shortlink" href="https://salesianmissions.org/?p=97"><link rel="alternate" type="application/json+oembed" href="/sites/all/themes/salesianmissions2/linked/wp-jsonoembed/1.0/embed?url=https%3A%2F%2Fsalesianmissions.org%2Fabout-us%2Fnews-publications%2Fsalesian-magazine%2F"><link rel="alternate" type="text/xml+oembed" href="/sites/all/themes/salesianmissions2/linked/wp-jsonoembed/1.0/embed?url=https%3A%2F%2Fsalesianmissions.org%2Fabout-us%2Fnews-publications%2Fsalesian-magazine%2F&amp;format=xml"><!--[if lt IE 9]>
<script src="/sites/all/themes/salesianmissions2/js/html5shiv.min.js"></script>
<![endif]--><meta name="generator" content="Powered by Visual Composer - drag and drop page builder for WordPress."><!--[if lte IE 9]><link rel="stylesheet" type="text/css" href="/sites/all/themes/salesianmissions2/css/vc_lte_ie9.min.css" media="screen"><![endif]--><link rel="icon" href="/sites/all/themes/salesianmissions2/linked/salesian-favicon.png" sizes="32x32"><link rel="icon" href="/sites/all/themes/salesianmissions2/linked/salesian-favicon.png" sizes="192x192"><link rel="apple-touch-icon-precomposed" href="/sites/all/themes/salesianmissions2/linked/salesian-favicon.png"><meta name="msapplication-TileImage" content="/sites/all/themes/salesianmissions2/linked/salesian-favicon.png"><style type="text/css" data-type="vc_shortcodes-custom-css">.vc_custom_1496660911422{background: #009edd url(/sites/all/themes/salesianmissions2/cssAssets/get-involved-bg.png) !important;}</style><noscript><style type="text/css"> .wpb_animate_when_almost_visible { opacity: 1; }</style></noscript><style type="text/css">/** Mega Menu CSS: fs **/</style>
<?php
print $head;
print $styles;
print $scripts;
?>
<!--[if IE 7]>
<link rel="stylesheet" href="/sites/all/themes/pgcalc_master/ie7/ie7.css">
<![endif]-->
</head>
<?php
print $page_top;
print $page;
print $page_bottom;
?>
</html>
