<!--[if lte IE 9]>
<body class="ie">
<![endif]--><!--[if !IE]> --><body>
<!-- <![endif]-->
<div class="nav-back"></div>
    <header id="top"><div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-4">
                    <a href="https://spcatampabay.org"><div class="logo">
                        <div class="spca-logo"></div>
                    </div></a>
                    <div class="mobile-menu">
                        
<!-- UberMenu [Configuration:main] [Theme Loc:main-menu] [Integration:auto] -->
<a class="ubermenu-responsive-toggle ubermenu-responsive-toggle-main ubermenu-skin-none ubermenu-loc-main-menu" data-ubermenu-target="ubermenu-main-2-main-menu"><i class="fa fa-bars"></i>&#9776;</a><nav id="ubermenu-main-2-main-menu" class="ubermenu ubermenu-nojs ubermenu-main ubermenu-menu-2 ubermenu-loc-main-menu ubermenu-responsive ubermenu-responsive-767 ubermenu-responsive-collapse ubermenu-horizontal ubermenu-transition-shift ubermenu-trigger-hover_intent ubermenu-skin-none  ubermenu-bar-align-full ubermenu-items-align-left ubermenu-bound ubermenu-disable-submenu-scroll ubermenu-sub-indicators ubermenu-retractors-responsive"><ul id="ubermenu-nav-main-2-main-menu" class="ubermenu-nav"><li id="menu-item-5943" class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-5943 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-drop ubermenu-has-submenu-mega ubermenu-hide-desktop">
<a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">Make a Donation</span></a><ul class="ubermenu-submenu ubermenu-submenu-id-5943 ubermenu-submenu-type-auto ubermenu-submenu-type-mega ubermenu-submenu-drop ubermenu-submenu-align-full_width"><li id="menu-item-5944" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-5944 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-hide-desktop"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://spcatampabay.org/donate/"><span class="ubermenu-target-title ubermenu-target-text">One-Time Donations</span></a></li>
<li id="menu-item-949" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-949 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-hide-desktop"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://spcatampabay.org/monthly-donation/"><span class="ubermenu-target-title ubermenu-target-text">Monthly Donation</span></a></li>
<li id="menu-item-5945" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-5945 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-hide-desktop"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://spcatampabay.org/tribute/"><span class="ubermenu-target-title ubermenu-target-text">Tributes &amp; Memorials</span></a></li>
</ul></li>
<li id="menu-item-251" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-251 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto ubermenu-hide-desktop"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://spcatampabay.org/help-rescue-animals/" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">All the Ways You Can Help</span></a></li>
<li id="menu-item-240" class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-240 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-drop ubermenu-has-submenu-mega">
<a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">Adoptions</span></a><ul class="ubermenu-submenu ubermenu-submenu-id-240 ubermenu-submenu-type-mega ubermenu-submenu-drop ubermenu-submenu-align-center"><li id="menu-item-35" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-35 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-1 ubermenu-column ubermenu-column-natural"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/adopt-dogs-puppies/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/dog-icon.png" width="120" height="120" alt="dog-icon"><span class="ubermenu-target-title ubermenu-target-text">Dogs &amp; Puppies</span></a></li>
<li id="menu-item-34" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-34 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-1 ubermenu-column ubermenu-column-natural"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/adopt-cats-kittens/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/cat-icon.png" width="120" height="120" alt="cat-icon"><span class="ubermenu-target-title ubermenu-target-text">Cats &amp; Kittens</span></a></li>
<li id="menu-item-33" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-33 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-1 ubermenu-column ubermenu-column-natural"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/adopt-pet-rabbit/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/rabbit-icon.png" width="120" height="120" alt="rabbit-icon"><span class="ubermenu-target-title ubermenu-target-text">Rabbits &amp; Other Critters</span></a></li>
</ul></li>
<li id="menu-item-241" class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-241 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-drop ubermenu-has-submenu-mega">
<a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">Pet Health</span></a><ul class="ubermenu-submenu ubermenu-submenu-id-241 ubermenu-submenu-type-mega ubermenu-submenu-drop ubermenu-submenu-align-center"><li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-68 ubermenu-item-level-1 ubermenu-column ubermenu-column-1-4 ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-68"><ul class="ubermenu-submenu ubermenu-submenu-id-68 ubermenu-submenu-type-stack"><li id="menu-item-4206" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-4206 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-natural"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/veterinary-center/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/Veterinary-Center-icon2.png" width="120" height="120" alt="veterinary-center-icon2"><span class="ubermenu-target-title ubermenu-target-text">St. Pete Veterinary Center</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-69 ubermenu-item-level-1 ubermenu-column ubermenu-column-1-4 ubermenu-item-type-column ubermenu-column-id-69">
</li><li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-70 ubermenu-item-level-1 ubermenu-column ubermenu-column-1-4 ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-70"><ul class="ubermenu-submenu ubermenu-submenu-id-70 ubermenu-submenu-type-stack"><li id="menu-item-58" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-58 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-natural"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/pet-spay-neuter/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/spay-icon.png" width="120" height="120" alt="spay-icon"><span class="ubermenu-target-title ubermenu-target-text">Spay/Neuter Your Pet</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-advanced-sub ubermenu-item-71 ubermenu-item-level-1 ubermenu-column ubermenu-column-natural ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-71"><div class="ubermenu-submenu ubermenu-submenu-id-71 ubermenu-submenu-type-stack">
<ul class="ubermenu-row ubermenu-row-id-4204 ubermenu-autoclear "><li id="menu-item-4208" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-4208 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-natural"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/pet-wellness-tips/"><span class="ubermenu-target-title ubermenu-target-text">Wellness Tips</span></a></li></ul><ul class="ubermenu-row ubermenu-row-id-77 ubermenu-autoclear "><li id="menu-item-105" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-105 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-natural"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/pet-animal-transportation/"><span class="ubermenu-target-title ubermenu-target-text">Emergency Animal <br> Transportation</span></a></li></ul><ul class="ubermenu-row ubermenu-row-id-78 ubermenu-autoclear "><li id="menu-item-56" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-56 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-natural"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/pet-gift-shop/"><span class="ubermenu-target-title ubermenu-target-text">Homeward Bound Gift Shop</span></a></li></ul></div></li>
</ul></li>
<li id="menu-item-242" class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-242 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-drop ubermenu-has-submenu-mega">
<a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">Animal Help</span></a><ul class="ubermenu-submenu ubermenu-submenu-id-242 ubermenu-submenu-type-mega ubermenu-submenu-drop ubermenu-submenu-align-center"><li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-110 ubermenu-item-level-1 ubermenu-column ubermenu-column-natural ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-110"><ul class="ubermenu-submenu ubermenu-submenu-id-110 ubermenu-submenu-type-stack"><li id="menu-item-104" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-104 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/animal-cruelty/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/cruelty-icon.png" width="120" height="120" alt="cruelty-icon"><span class="ubermenu-target-title ubermenu-target-text">Cruelty Investigation</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-111 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-111"><ul class="ubermenu-submenu ubermenu-submenu-id-111 ubermenu-submenu-type-stack"><li id="menu-item-108" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-108 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/surrender-an-animal/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/surrender-icon.png" width="120" height="120" alt="surrender-icon"><span class="ubermenu-target-title ubermenu-target-text">Surrender an Animal</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-112 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-112"><ul class="ubermenu-submenu ubermenu-submenu-id-112 ubermenu-submenu-type-stack"><li id="menu-item-107" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-107 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/lost-found-animals/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/lost-icon.png" width="120" height="120" alt="lost-icon"><span class="ubermenu-target-title ubermenu-target-text">Lost &amp; Found Animals</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-advanced-sub ubermenu-item-113 ubermenu-item-level-1 ubermenu-column ubermenu-column-natural ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-113"><div class="ubermenu-submenu ubermenu-submenu-id-113 ubermenu-submenu-type-stack">
<ul class="ubermenu-row ubermenu-row-id-76 ubermenu-autoclear "><li id="menu-item-57" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-57 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/pet-euthanasia-cremation/"><span class="ubermenu-target-title ubermenu-target-text">Largo Pet Euthanasia &amp; Cremation</span></a></li></ul><ul class="ubermenu-row ubermenu-row-id-115 ubermenu-autoclear "><li id="menu-item-106" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-106 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/pet-food-bank/"><span class="ubermenu-target-title ubermenu-target-text">Food Bank</span></a></li></ul><ul class="ubermenu-row ubermenu-row-id-116 ubermenu-autoclear "><li id="menu-item-109" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-109 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/wildlife-rescue-rehabilitation/"><span class="ubermenu-target-title ubermenu-target-text">Wildlife Rescue &amp; Rehabilitation</span></a></li></ul></div></li>
</ul></li>
<li id="menu-item-243" class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-243 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-drop ubermenu-has-submenu-mega">
<a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">Training</span></a><ul class="ubermenu-submenu ubermenu-submenu-id-243 ubermenu-submenu-type-mega ubermenu-submenu-drop ubermenu-submenu-align-center"><li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-152 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-152"><ul class="ubermenu-submenu ubermenu-submenu-id-152 ubermenu-submenu-type-stack"><li id="menu-item-145" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-145 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-natural"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/dog-training-resources/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/dog-classes-icon.png" width="120" height="120" alt="dog-classes-icon"><span class="ubermenu-target-title ubermenu-target-text">Dog Training Resources</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-6949 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-6949"><ul class="ubermenu-submenu ubermenu-submenu-id-6949 ubermenu-submenu-type-stack"><li id="menu-item-6948" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-6948 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above" href="https://spcatampabay.org/pet-behavior-help/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/tutor-icon.png" width="120" height="120" alt="tutor-icon"><span class="ubermenu-target-title ubermenu-target-text">Pet Behavior Help</span></a></li></ul></li>
</ul></li>
<li id="menu-item-244" class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-244 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-drop ubermenu-has-submenu-mega">
<a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">Get Involved</span></a><ul class="ubermenu-submenu ubermenu-submenu-id-244 ubermenu-submenu-type-mega ubermenu-submenu-drop ubermenu-submenu-align-right_edge_bar"><li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-194 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-194"><ul class="ubermenu-submenu ubermenu-submenu-id-194 ubermenu-submenu-type-stack"><li id="menu-item-190" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-190 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/event-calendar/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/event-calendar-icon.png" width="123" height="120" alt="event-calendar-icon"><span class="ubermenu-target-title ubermenu-target-text">Event Calendar</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-195 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-195"><ul class="ubermenu-submenu ubermenu-submenu-id-195 ubermenu-submenu-type-stack"><li id="menu-item-192" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-192 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/petwalk/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/pet-walk-icon.png" width="120" height="120" alt="pet-walk-icon"><span class="ubermenu-target-title ubermenu-target-text">Pet Walk</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-197 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-197"><ul class="ubermenu-submenu ubermenu-submenu-id-197 ubermenu-submenu-type-stack"><li id="menu-item-187" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-187 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/pet-camps-workshops/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/camps-youth-programs.png" width="120" height="120" alt="camps-youth-programs"><span class="ubermenu-target-title ubermenu-target-text">Camps &amp; Youth Programs</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-advanced-sub ubermenu-item-198 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-198"><div class="ubermenu-submenu ubermenu-submenu-id-198 ubermenu-submenu-type-stack">
<ul class="ubermenu-row ubermenu-row-id-199 ubermenu-autoclear "><li id="menu-item-189" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-189 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/careers/"><span class="ubermenu-target-title ubermenu-target-text">Employment Opportunities</span></a></li></ul><ul class="ubermenu-row ubermenu-row-id-200 ubermenu-autoclear "><li id="menu-item-193" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-193 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/volunteer/"><span class="ubermenu-target-title ubermenu-target-text">Volunteer Opportunities</span></a></li></ul><ul class="ubermenu-row ubermenu-row-id-201 ubermenu-autoclear "><li id="menu-item-188" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-188 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/donate-items/"><span class="ubermenu-target-title ubermenu-target-text">Donate Items</span></a></li></ul></div></li>
</ul></li>
<li id="menu-item-245" class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-current-menu-ancestor ubermenu-item-has-children ubermenu-item-245 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-drop ubermenu-has-submenu-mega">
<a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">About Us</span></a><ul class="ubermenu-submenu ubermenu-submenu-id-245 ubermenu-submenu-type-mega ubermenu-submenu-drop ubermenu-submenu-align-right_edge_bar"><li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-196 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-196"><ul class="ubermenu-submenu ubermenu-submenu-id-196 ubermenu-submenu-type-stack"><li id="menu-item-3030" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-3030 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/ambassadors/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/120x1202.png" width="120" height="120" alt="120&times;1202"><span class="ubermenu-target-title ubermenu-target-text">Our Ambassadors</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-228 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-228"><ul class="ubermenu-submenu ubermenu-submenu-id-228 ubermenu-submenu-type-stack"><li id="menu-item-221" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-221 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/about/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/general-info-icon.png" width="120" height="120" alt="general-info-icon"><span class="ubermenu-target-title ubermenu-target-text">General Information</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-current-menu-ancestor ubermenu-current-menu-parent ubermenu-item-has-children ubermenu-item-229 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-229"><ul class="ubermenu-submenu ubermenu-submenu-id-229 ubermenu-submenu-type-stack"><li id="menu-item-223" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-current-menu-item ubermenu-page_item ubermenu-page-item-208 ubermenu-current_page_item ubermenu-item-223 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/our-team/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/our-team-icon.png" width="120" height="120" alt="our-team-icon"><span class="ubermenu-target-title ubermenu-target-text">Our Team</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-230 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-230"><ul class="ubermenu-submenu ubermenu-submenu-id-230 ubermenu-submenu-type-stack"><li id="menu-item-220" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-220 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/animal-statistics/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/animal-stats-icon.png" width="120" height="120" alt="animal-stats-icon"><span class="ubermenu-target-title ubermenu-target-text">Animal Statistics</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-advanced-sub ubermenu-item-238 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-238"><div class="ubermenu-submenu ubermenu-submenu-id-238 ubermenu-submenu-type-stack">
<ul class="ubermenu-row ubermenu-row-id-232 ubermenu-autoclear "><li id="menu-item-222" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-222 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/news/"><span class="ubermenu-target-title ubermenu-target-text">In the News</span></a></li></ul><ul class="ubermenu-row ubermenu-row-id-233 ubermenu-autoclear "><li id="menu-item-224" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-224 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/tours/"><span class="ubermenu-target-title ubermenu-target-text">Tours</span></a></li></ul><ul class="ubermenu-row ubermenu-row-id-234 ubermenu-autoclear "><li id="menu-item-227" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-227 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/financials/"><span class="ubermenu-target-title ubermenu-target-text">Financial Information</span></a></li></ul></div></li>
</ul></li>
</ul></nav><!-- End UberMenu --></div>
                </div>
                <div class="col-md-9 col-sm-8">
                    <div class="donate section">
                        <a href="https://spcatampabay.org/one-time-donation/"><div class="button donate">make a donation</div></a>
                        <ul><li class="first"><a href="https://spcatampabay.org/monthly-donation/">GIVE MONTHLY</a></li>
                            <li class="last"><a href="https://spcatampabay.org/tribute/">MEMORIAL GIVING</a></li>
                        </ul></div>
                    <div class="ways-to-help section">
                        <a href="https://spcatampabay.org/help-rescue-animals/"><div class="button ways-to-help">all the ways you can help</div></a>
                    </div>            
                </div>
            </div>
        </div>
    </header><article><div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="desktop-menu">
                        
<!-- UberMenu [Configuration:main] [Theme Loc:main-menu] [Integration:auto] -->
<a class="ubermenu-responsive-toggle ubermenu-responsive-toggle-main ubermenu-skin-none ubermenu-loc-main-menu" data-ubermenu-target="ubermenu-main-2-main-menu-2"><i class="fa fa-bars"></i>&#9776;</a><nav id="ubermenu-main-2-main-menu-2" class="ubermenu ubermenu-nojs ubermenu-main ubermenu-menu-2 ubermenu-loc-main-menu ubermenu-responsive ubermenu-responsive-767 ubermenu-responsive-collapse ubermenu-horizontal ubermenu-transition-shift ubermenu-trigger-hover_intent ubermenu-skin-none  ubermenu-bar-align-full ubermenu-items-align-left ubermenu-bound ubermenu-disable-submenu-scroll ubermenu-sub-indicators ubermenu-retractors-responsive"><ul id="ubermenu-nav-main-2-main-menu" class="ubermenu-nav"><li class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-5943 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-drop ubermenu-has-submenu-mega ubermenu-hide-desktop">
<a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">Make a Donation</span></a><ul class="ubermenu-submenu ubermenu-submenu-id-5943 ubermenu-submenu-type-auto ubermenu-submenu-type-mega ubermenu-submenu-drop ubermenu-submenu-align-full_width"><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-5944 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-hide-desktop"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://spcatampabay.org/donate/"><span class="ubermenu-target-title ubermenu-target-text">One-Time Donations</span></a></li>
<li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-949 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-hide-desktop"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://spcatampabay.org/monthly-donation/"><span class="ubermenu-target-title ubermenu-target-text">Monthly Donation</span></a></li>
<li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-5945 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-hide-desktop"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://spcatampabay.org/tribute/"><span class="ubermenu-target-title ubermenu-target-text">Tributes &amp; Memorials</span></a></li>
</ul></li>
<li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-251 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto ubermenu-hide-desktop"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://spcatampabay.org/help-rescue-animals/" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">All the Ways You Can Help</span></a></li>
<li class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-240 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-drop ubermenu-has-submenu-mega">
<a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">Adoptions</span></a><ul class="ubermenu-submenu ubermenu-submenu-id-240 ubermenu-submenu-type-mega ubermenu-submenu-drop ubermenu-submenu-align-center"><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-35 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-1 ubermenu-column ubermenu-column-natural"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/adopt-dogs-puppies/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/dog-icon.png" width="120" height="120" alt="dog-icon"><span class="ubermenu-target-title ubermenu-target-text">Dogs &amp; Puppies</span></a></li>
<li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-34 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-1 ubermenu-column ubermenu-column-natural"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/adopt-cats-kittens/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/cat-icon.png" width="120" height="120" alt="cat-icon"><span class="ubermenu-target-title ubermenu-target-text">Cats &amp; Kittens</span></a></li>
<li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-33 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-1 ubermenu-column ubermenu-column-natural"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/adopt-pet-rabbit/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/rabbit-icon.png" width="120" height="120" alt="rabbit-icon"><span class="ubermenu-target-title ubermenu-target-text">Rabbits &amp; Other Critters</span></a></li>
</ul></li>
<li class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-241 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-drop ubermenu-has-submenu-mega">
<a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">Pet Health</span></a><ul class="ubermenu-submenu ubermenu-submenu-id-241 ubermenu-submenu-type-mega ubermenu-submenu-drop ubermenu-submenu-align-center"><li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-68 ubermenu-item-level-1 ubermenu-column ubermenu-column-1-4 ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-68"><ul class="ubermenu-submenu ubermenu-submenu-id-68 ubermenu-submenu-type-stack"><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-4206 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-natural"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/veterinary-center/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/Veterinary-Center-icon2.png" width="120" height="120" alt="veterinary-center-icon2"><span class="ubermenu-target-title ubermenu-target-text">St. Pete Veterinary Center</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-69 ubermenu-item-level-1 ubermenu-column ubermenu-column-1-4 ubermenu-item-type-column ubermenu-column-id-69">
</li><li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-70 ubermenu-item-level-1 ubermenu-column ubermenu-column-1-4 ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-70"><ul class="ubermenu-submenu ubermenu-submenu-id-70 ubermenu-submenu-type-stack"><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-58 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-natural"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/pet-spay-neuter/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/spay-icon.png" width="120" height="120" alt="spay-icon"><span class="ubermenu-target-title ubermenu-target-text">Spay/Neuter Your Pet</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-advanced-sub ubermenu-item-71 ubermenu-item-level-1 ubermenu-column ubermenu-column-natural ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-71"><div class="ubermenu-submenu ubermenu-submenu-id-71 ubermenu-submenu-type-stack">
<ul class="ubermenu-row ubermenu-row-id-4204 ubermenu-autoclear "><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-4208 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-natural"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/pet-wellness-tips/"><span class="ubermenu-target-title ubermenu-target-text">Wellness Tips</span></a></li></ul><ul class="ubermenu-row ubermenu-row-id-77 ubermenu-autoclear "><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-105 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-natural"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/pet-animal-transportation/"><span class="ubermenu-target-title ubermenu-target-text">Emergency Animal <br> Transportation</span></a></li></ul><ul class="ubermenu-row ubermenu-row-id-78 ubermenu-autoclear "><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-56 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-natural"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/pet-gift-shop/"><span class="ubermenu-target-title ubermenu-target-text">Homeward Bound Gift Shop</span></a></li></ul></div></li>
</ul></li>
<li class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-242 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-drop ubermenu-has-submenu-mega">
<a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">Animal Help</span></a><ul class="ubermenu-submenu ubermenu-submenu-id-242 ubermenu-submenu-type-mega ubermenu-submenu-drop ubermenu-submenu-align-center"><li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-110 ubermenu-item-level-1 ubermenu-column ubermenu-column-natural ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-110"><ul class="ubermenu-submenu ubermenu-submenu-id-110 ubermenu-submenu-type-stack"><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-104 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/animal-cruelty/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/cruelty-icon.png" width="120" height="120" alt="cruelty-icon"><span class="ubermenu-target-title ubermenu-target-text">Cruelty Investigation</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-111 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-111"><ul class="ubermenu-submenu ubermenu-submenu-id-111 ubermenu-submenu-type-stack"><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-108 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/surrender-an-animal/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/surrender-icon.png" width="120" height="120" alt="surrender-icon"><span class="ubermenu-target-title ubermenu-target-text">Surrender an Animal</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-112 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-112"><ul class="ubermenu-submenu ubermenu-submenu-id-112 ubermenu-submenu-type-stack"><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-107 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/lost-found-animals/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/lost-icon.png" width="120" height="120" alt="lost-icon"><span class="ubermenu-target-title ubermenu-target-text">Lost &amp; Found Animals</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-advanced-sub ubermenu-item-113 ubermenu-item-level-1 ubermenu-column ubermenu-column-natural ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-113"><div class="ubermenu-submenu ubermenu-submenu-id-113 ubermenu-submenu-type-stack">
<ul class="ubermenu-row ubermenu-row-id-76 ubermenu-autoclear "><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-57 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/pet-euthanasia-cremation/"><span class="ubermenu-target-title ubermenu-target-text">Largo Pet Euthanasia &amp; Cremation</span></a></li></ul><ul class="ubermenu-row ubermenu-row-id-115 ubermenu-autoclear "><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-106 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/pet-food-bank/"><span class="ubermenu-target-title ubermenu-target-text">Food Bank</span></a></li></ul><ul class="ubermenu-row ubermenu-row-id-116 ubermenu-autoclear "><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-109 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/wildlife-rescue-rehabilitation/"><span class="ubermenu-target-title ubermenu-target-text">Wildlife Rescue &amp; Rehabilitation</span></a></li></ul></div></li>
</ul></li>
<li class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-243 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-drop ubermenu-has-submenu-mega">
<a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">Training</span></a><ul class="ubermenu-submenu ubermenu-submenu-id-243 ubermenu-submenu-type-mega ubermenu-submenu-drop ubermenu-submenu-align-center"><li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-152 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-152"><ul class="ubermenu-submenu ubermenu-submenu-id-152 ubermenu-submenu-type-stack"><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-145 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-natural"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/dog-training-resources/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/dog-classes-icon.png" width="120" height="120" alt="dog-classes-icon"><span class="ubermenu-target-title ubermenu-target-text">Dog Training Resources</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-6949 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-6949"><ul class="ubermenu-submenu ubermenu-submenu-id-6949 ubermenu-submenu-type-stack"><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-6948 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above" href="https://spcatampabay.org/pet-behavior-help/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/tutor-icon.png" width="120" height="120" alt="tutor-icon"><span class="ubermenu-target-title ubermenu-target-text">Pet Behavior Help</span></a></li></ul></li>
</ul></li>
<li class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-244 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-drop ubermenu-has-submenu-mega">
<a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">Get Involved</span></a><ul class="ubermenu-submenu ubermenu-submenu-id-244 ubermenu-submenu-type-mega ubermenu-submenu-drop ubermenu-submenu-align-right_edge_bar"><li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-194 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-194"><ul class="ubermenu-submenu ubermenu-submenu-id-194 ubermenu-submenu-type-stack"><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-190 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/event-calendar/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/event-calendar-icon.png" width="123" height="120" alt="event-calendar-icon"><span class="ubermenu-target-title ubermenu-target-text">Event Calendar</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-195 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-195"><ul class="ubermenu-submenu ubermenu-submenu-id-195 ubermenu-submenu-type-stack"><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-192 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/petwalk/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/pet-walk-icon.png" width="120" height="120" alt="pet-walk-icon"><span class="ubermenu-target-title ubermenu-target-text">Pet Walk</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-197 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-197"><ul class="ubermenu-submenu ubermenu-submenu-id-197 ubermenu-submenu-type-stack"><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-187 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/pet-camps-workshops/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/camps-youth-programs.png" width="120" height="120" alt="camps-youth-programs"><span class="ubermenu-target-title ubermenu-target-text">Camps &amp; Youth Programs</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-advanced-sub ubermenu-item-198 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-198"><div class="ubermenu-submenu ubermenu-submenu-id-198 ubermenu-submenu-type-stack">
<ul class="ubermenu-row ubermenu-row-id-199 ubermenu-autoclear "><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-189 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/careers/"><span class="ubermenu-target-title ubermenu-target-text">Employment Opportunities</span></a></li></ul><ul class="ubermenu-row ubermenu-row-id-200 ubermenu-autoclear "><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-193 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/volunteer/"><span class="ubermenu-target-title ubermenu-target-text">Volunteer Opportunities</span></a></li></ul><ul class="ubermenu-row ubermenu-row-id-201 ubermenu-autoclear "><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-188 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/donate-items/"><span class="ubermenu-target-title ubermenu-target-text">Donate Items</span></a></li></ul></div></li>
</ul></li>
<li class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-current-menu-ancestor ubermenu-item-has-children ubermenu-item-245 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-drop ubermenu-has-submenu-mega">
<a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">About Us</span></a><ul class="ubermenu-submenu ubermenu-submenu-id-245 ubermenu-submenu-type-mega ubermenu-submenu-drop ubermenu-submenu-align-right_edge_bar"><li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-196 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-196"><ul class="ubermenu-submenu ubermenu-submenu-id-196 ubermenu-submenu-type-stack"><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-3030 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/ambassadors/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/120x1202.png" width="120" height="120" alt="120&times;1202"><span class="ubermenu-target-title ubermenu-target-text">Our Ambassadors</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-228 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-228"><ul class="ubermenu-submenu ubermenu-submenu-id-228 ubermenu-submenu-type-stack"><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-221 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/about/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/general-info-icon.png" width="120" height="120" alt="general-info-icon"><span class="ubermenu-target-title ubermenu-target-text">General Information</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-current-menu-ancestor ubermenu-current-menu-parent ubermenu-item-has-children ubermenu-item-229 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-229"><ul class="ubermenu-submenu ubermenu-submenu-id-229 ubermenu-submenu-type-stack"><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-current-menu-item ubermenu-page_item ubermenu-page-item-208 ubermenu-current_page_item ubermenu-item-223 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/our-team/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/our-team-icon.png" width="120" height="120" alt="our-team-icon"><span class="ubermenu-target-title ubermenu-target-text">Our Team</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-item-230 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-230"><ul class="ubermenu-submenu ubermenu-submenu-id-230 ubermenu-submenu-type-stack"><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-220 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-image_above icon-link" href="https://spcatampabay.org/animal-statistics/"><img class="ubermenu-image ubermenu-image-size-full" src="/sites/all/themes/diaspark10/img/animal-stats-icon.png" width="120" height="120" alt="animal-stats-icon"><span class="ubermenu-target-title ubermenu-target-text">Animal Statistics</span></a></li></ul></li>
<li class="  ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-has-children ubermenu-advanced-sub ubermenu-item-238 ubermenu-item-level-1 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack ubermenu-item-type-column ubermenu-column-id-238"><div class="ubermenu-submenu ubermenu-submenu-id-238 ubermenu-submenu-type-stack">
<ul class="ubermenu-row ubermenu-row-id-232 ubermenu-autoclear "><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-222 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/news/"><span class="ubermenu-target-title ubermenu-target-text">In the News</span></a></li></ul><ul class="ubermenu-row ubermenu-row-id-233 ubermenu-autoclear "><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-224 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/tours/"><span class="ubermenu-target-title ubermenu-target-text">Tours</span></a></li></ul><ul class="ubermenu-row ubermenu-row-id-234 ubermenu-autoclear "><li class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-227 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only list-link" href="https://spcatampabay.org/financials/"><span class="ubermenu-target-title ubermenu-target-text">Financial Information</span></a></li></ul></div></li>
</ul></li>
</ul></nav><!-- End UberMenu --></div>
                </div>
            </div>
<div class="row">
    <div class="col-md-12">
        <h1>Our Team</h1>     </div>
</div>
<div class="row">
    <div class="col-md-3"><?php print render($page['menu']); ?></div>
    <div class="col-md-9">
    
        <div class="content about-us"><?php require(DRUPAL_ROOT."/sites/all/themes/pgcalc_master/page.content.tpl.php"); ?></div>
    </div>
</div>

            
            <div class="row">
                <div class="col-md-12">
                    <footer><div class="row">
                            <div class="col-md-6">
                                <div class="content">
                                    <h3>Largo Shelter</h3>
                                    <p class="large">9099 130th Avenue North<br>Largo, Florida 33773</p>
                                    <a href="http://maps.google.com/maps?daddr=9099+130th+Avenue+North+Largo,+Florida+33773" target="_blank"><div class="button">view in google maps</div></a>
                                                                        <h4>Shelter Hours:</h4>
                                    <p>Tuesday &ndash; Friday: 1:00 p.m. - 7:00 p.m.</p>
<p>Saturday: 10:00 a.m. - 6:00 p.m.</p>
<p>Sunday: 1:00 p.m. - 5:00 p.m.</p>
<p>&nbsp;</p>
                                                                    </div>
                            </div>
                            <div class="col-md-6">
                                <div class="content">
                                    <h3>Veterinary Center</h3>
                                    <p class="large">3250 5th Avenue North<br>St. Petersburg, Florida 33713</p>
                                    <a href="https://www.google.com/maps/dir/3250+5th+Avenue+North,+Saint+Petersburg,+FL+33713" target="_blank"><div class="button">view in google maps</div></a>
                                                                        <h4>Veterinary Center Hours:</h4>
                                    <p>Monday &ndash; Friday: 7:30 a.m. &ndash; 6:00 p.m.*<br>
Saturday: 8:00 a.m. &ndash; 4:00 p.m.</p>
<p>*Closed 12:30 p.m. -1:30 p.m. every 3rd &amp; 4th Tuesday of the month</p>
                                                                    </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="content">
                                    <h3>Get in touch</h3>
                                                                        <div class="numbers">
                                        <div class="left">
                                            <p>Shelter Phone:</p>
                                        </div>
                                        <div class="right">
                                            <p>727-586-3591</p>
                                        </div>
                                    </div>
                                                                        <div class="numbers">
                                        <div class="left">
                                            <p>Shelter Fax:</p>
                                        </div>
                                        <div class="right">
                                            <p>727-499-0368</p>
                                        </div>
                                    </div>
                                                                        <div class="numbers">
                                        <div class="left">
                                            <p>Cruelty Investigation Hotline:</p>
                                        </div>
                                        <div class="right">
                                            <p>727-586-3592</p>
                                        </div>
                                    </div>
                                                                        <div class="numbers">
                                        <div class="left">
                                            <p>Animal Transport:</p>
                                        </div>
                                        <div class="right">
                                            <p>727-586-3592</p>
                                        </div>
                                    </div>
                                                                        <div class="numbers">
                                        <div class="left">
                                            <p>Pet Behavior Tipline:</p>
                                        </div>
                                        <div class="right">
                                            <p>727-586-3593</p>
                                        </div>
                                    </div>
                                                                        <div class="numbers">
                                        <div class="left">
                                            <p>Donations:</p>
                                        </div>
                                        <div class="right">
                                            <p>727-388-0450</p>
                                        </div>
                                    </div>
                                                                        <div class="numbers">
                                        <div class="left">
                                            <p>Pet &amp; Estate Planning Tools:</p>
                                        </div>
                                        <div class="right">
                                            <p>727-581-3249</p>
                                        </div>
                                    </div>
                                                                    </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="content">
                                    <h3>Get in touch</h3>
                                                                        <div class="numbers">
                                        <div class="left">
                                            <p>Veterinary Center Phone:</p>
                                        </div>
                                        <div class="right">
                                            <p>727-220-1770</p>
                                        </div>
                                    </div>
                                                                        <div class="numbers">
                                        <div class="left">
                                            <p>Veterinary Center Fax:</p>
                                        </div>
                                        <div class="right">
                                            <p>727-220-1721</p>
                                        </div>
                                    </div>
                                                                        <h3 class="margin-top">stay in touch.</h3>
                                    <form action="post" class="mailing-list-signup-form">
                                        <input type="text" id="first_name" name="first_name" placeholder="First Name"><input type="text" id="last_name" name="last_name" placeholder="Last Name"><input type="text" id="email" name="email" placeholder="Email Address"><input type="hidden" value="1446009134" name="list" id="list"><div class="button">sign up for our e-newsletter</div>
                                        <div id="ajax-message"></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </footer><div class="footer-bottom">
                        <div class="col-md-3">
                            <ul><li><a href="https://www.facebook.com/SPCATampaBay" target="_blank"><div class="icon" id="facebook"></div></a></li>
                                <li><a href="https://www.instagram.com/spcatampabay/" target="_blank"><div class="icon" id="instagram"></div></a></li>
                                <li><a href="https://www.youtube.com/user/SPCATampaBay" target="_blank"><div class="icon" id="youtube"></div></a></li>
                            </ul></div>
                        <div class="col-md-7">
                            <p>&copy; 2017 SPCA Tampa Bay. All Rights Reserved. <a href="https://spcatampabay.org/privacy-policy/">Privacy Policy</a></p>
                            <p>A COPY OF THE OFFICIAL REGISTRATION (CH-#1173) AND FINANCIAL INFORMATION MAY BE OBTAINED FROM THE DIVISION OF CONSUMER SERVICES ON ITS WEBSITE (WWW.800HELPFLA.COM) OR BY CALLING TOLL-FREE <span>800-435-7352</span> WITHIN THE STATE. REGISTRATION DOES NOT IMPLY ENDORSEMENT. APPROVAL OR RECOMMENDATION BY THE STATE.</p>
                        </div>
                        <div class="col-md-2">
                            <img class="img-responsive" src="/sites/all/themes/diaspark10/img/hills-logo.png" alt=""></div>
                    </div>
                </div>
            </div>
        </div>
    </article><script src="/sites/all/themes/diaspark10/js/jquery.min.js"></script><script src="/sites/all/themes/diaspark10/js/modernizr.js"></script><script src="/sites/all/themes/diaspark10/js/jquery.flexslider-min.js"></script><script src="/sites/all/themes/diaspark10/js/bootstrap.min.js"></script><script src="/sites/all/themes/diaspark10/js/main.js"></script><script>
            (function () {
                $('.ubermenu-item-245').addClass('on-page');
            })();
        </script><script type="text/javascript">
/* <![CDATA[ */
var wpcf7 = {"apiSettings":{"root":"https:\/\/spcatampabay.org\/wp-json\/","namespace":"contact-form-7\/v1"},"recaptcha":{"messages":{"empty":"Please verify that you are not a robot."}}};
/* ]]> */
</script><script type="text/javascript" src="/sites/all/themes/diaspark10/js/scripts.js"></script><script type="text/javascript" src="/sites/all/themes/diaspark10/js/jquery.qtip.min.js"></script><script type="text/javascript" src="/sites/all/themes/diaspark10/js/moment.min.js"></script><script type="text/javascript" src="/sites/all/themes/diaspark10/js/moment-timezone-with-data.min.js"></script><script type="text/javascript">
/* <![CDATA[ */
var simcal_default_calendar = {"ajax_url":"\/wp-admin\/admin-ajax.php","nonce":"f26497c337","locale":"en_US","text_dir":"ltr","months":{"full":["January","February","March","April","May","June","July","August","September","October","November","December"],"short":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]},"days":{"full":["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],"short":["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]},"meridiem":{"AM":"AM","am":"am","PM":"PM","pm":"pm"}};
var simcal_default_calendar = {"ajax_url":"\/wp-admin\/admin-ajax.php","nonce":"f26497c337","locale":"en_US","text_dir":"ltr","months":{"full":["January","February","March","April","May","June","July","August","September","October","November","December"],"short":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]},"days":{"full":["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],"short":["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]},"meridiem":{"AM":"AM","am":"am","PM":"PM","pm":"pm"}};
/* ]]> */
</script><script type="text/javascript" src="/sites/all/themes/diaspark10/js/default-calendar.min.js"></script><script type="text/javascript" src="/sites/all/themes/diaspark10/js/js"></script><script type="text/javascript">
/* <![CDATA[ */
var ubermenu_data = {"remove_conflicts":"on","reposition_on_load":"off","intent_delay":"300","intent_interval":"100","intent_threshold":"7","scrollto_offset":"50","scrollto_duration":"1000","responsive_breakpoint":"767","accessible":"on","retractor_display_strategy":"responsive","touch_off_close":"on","v":"3.2.0.2","ajax_url":"https:\/\/spcatampabay.org\/wp-admin\/admin-ajax.php"};
/* ]]> */
</script><script type="text/javascript" src="/sites/all/themes/diaspark10/js/ubermenu.min.js"></script><script type="text/javascript" src="/sites/all/themes/diaspark10/js/imagesloaded.pkgd.min.js"></script><script type="text/javascript" src="/sites/all/themes/diaspark10/js/wp-embed.min.js"></script><script data-cfasync="false">
      (function(a,b,c,d,e){var f=a+"Q";b[a]=b[a]||{};b[a][d]=b[a][d]||function(){
      (b[f]=b[f]||[]).push(arguments)};a=c.getElementsByTagName(e)[0];c=c.createElement(e);c.async=1;
      c.src="//static.reembed.com/data/scripts/g_7510_b5ea8875a6d710382a0f0caa1f775369.js";
      a.parentNode.insertBefore(c,a)})("reEmbed",window,document,"setupPlaylist","script");
    </script><script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-36017887-1', 'auto');
      ga('send', 'pageview');

    </script></body>