<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US"><head><meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><title><?php print $head_title; ?></title><link rel="stylesheet" href="/sites/all/themes/test/css/style.css?v=7" type="text/css"><meta name="viewport" content="width=device-width, initial-scale=1.0"><!--  IE-specific stylesheets --><!--[if lt IE 7]><link rel="stylesheet" href="/sites/all/themes/test/css/ie6.css"/><![endif]--><!--[if IE 7]><link rel="stylesheet" href="/sites/all/themes/test/css/ie7.css"/><![endif]--><meta name="DC.Date" content="2011-12-21"><link rel="publisher" href="/sites/all/themes/test/linked/110262710175914398931"><link rel="stylesheet" id="wheaton-fancybox-style-css" href="/sites/all/themes/test/css/ca68a32fff9f6337134d9772ed958158.4a?ver=1.3.4a" type="text/css" media="all"><link rel="stylesheet" id="ha_frontend-style-css" href="/sites/all/themes/test/linked/-1wp-content/plugins/hotspots/php/controllers/../../css/frontend.css?ver=3.9.1" type="text/css" media="all"><link rel="stylesheet" id="jquery-style-css" href="/sites/all/themes/test/css/jquery-ui.css?ver=3.9.1?ver=3.9.1" type="text/css" media="all"><script type="text/javascript" src="/sites/all/themes/test/linked/-1wp-includes/js/jquery/jquery.js?ver=1.11.0"></script><script type="text/javascript" src="/sites/all/themes/test/linked/-1wp-includes/js/jquery/jquery-migrate.min.js?ver=1.2.1"></script><link rel="canonical" href="/sites/all/themes/test/linked/-1gifts-protect-assets/"><link rel="shortlink" href="/sites/all/themes/test/linked/-1?p=61"><style type="text/css">
		#wpadminbar #adminbarsearch {
			display: none;
		}
		</style><script type="text/javascript" src="/sites/all/themes/test/linked/-1wp-admin/admin-ajax.php?viberjs=&amp;i=61"></script><style type="text/css">
        .home li#backhome { display: none; }        </style>
<?php
print $head;
print $styles;
print $scripts;
?>
<!--[if IE 7]>
<link rel="stylesheet" href="/sites/all/themes/pgcalc_master/ie7/ie7.css">
<![endif]-->
</head>
<?php
print $page_top;
print $page;
print $page_bottom;
?>
</html><!-- Dynamic page generated in 0.148 seconds. --><!-- Cached page generated by WP-Super-Cache on 2014-08-15 14:09:06 --><!-- super cache -->
