<body class="chapter-content-page-template-default single single-chapter-content-page postid-1625 is_chapter_page group-blog" original-class="chapter-content-page-template-default single single-chapter-content-page postid-1625 is_chapter_page group-blog">
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MSD33Q" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<div id="page" class="site" original-class="site">
<a class="skip-link screen-reader-text" original-class="skip-link screen-reader-text" href="#content">Skip to content</a><header id="masthead" class="site-header" original-class="site-header" role="banner"><div id="topBar" class="clear" original-class="clear"><div class="wrapper" original-class="wrapper"><div class="">
<div class="menu-top-left-container" original-class="menu-top-left-container"><ul id="top-left-menu-nav" class="menu" original-class="menu"><li id="menu-item-1488" class="apda-fa-home menu-item menu-item-type-custom menu-item-object-custom menu-item-1488" original-class="apda-fa-home menu-item menu-item-type-custom menu-item-object-custom menu-item-1488"><a href="https://www.apdaparkinson.org/">National Headquarters</a></li>
<li id="menu-item-5" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5" original-class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5"><a href="tel://www.apdaparkinson.org/community/northwest/upcoming-events-3/1-800-223-2732">1-800-223-2732</a></li>
</ul></div>
<div class="menu-top-right-container" original-class="menu-top-right-container"><ul id="top-right-menu-nav" class="menu" original-class="menu"><li class="menu-item" original-class="menu-item"><a href="https://www.apdaparkinson.org/community/" class=" fa-map-marker" original-class=" fa-map-marker">View Map</a></li>
<li class="menu-item change-location" original-class="menu-item change-location"><a href="https://www.apdaparkinson.org/community/" class="">Change Location</a></li>
</ul></div>
</div></div></div>
<div class="wrapper" original-class="wrapper"><div class="site-branding" original-class="site-branding">
<p class="site-title" original-class="site-title">
<a href="https://www.apdaparkinson.org/community/" rel="home"><img src="/sites/default/files/APDA_LogoTag_RGB_506width.png" alt="Chapter Events &amp; Programs | APDA Northwest" title="Chapter Events &amp; Programs | APDA Northwest" class="chapter-logo " original-class="chapter-logo "></a></p>
<div class="menu-header-right-about-menu-container" original-class="menu-header-right-about-menu-container"><ul id="header-right-menu-nav" class="menu" original-class="menu"><li id="menu-item-451" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-451" original-class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-451">
<a href="https://www.apdaparkinson.org/about-apda/">About APDA</a><ul class="sub-menu" original-class="sub-menu"><li id="menu-item-2281" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2281" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2281"><a href="https://www.apdaparkinson.org/about-apda/">Mission &amp; Leadership</a></li>
<li id="menu-item-2280" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2280" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2280"><a href="https://www.apdaparkinson.org/about-apda/strategic-plan/">2015-18 Strategic Plan</a></li>
<li id="menu-item-2279" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2279" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2279"><a href="https://www.apdaparkinson.org/about-apda/financial-reports/">Financial Reports</a></li>
<li id="menu-item-3089" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3089" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3089"><a href="https://www.apdaparkinson.org/about-apda/career-opportunities/">Career Opportunities</a></li>
</ul></li>
<li id="menu-item-1483" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1483" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1483"><a href="https://www.apdaparkinson.org/resources-support/en-espanol/">En Espa&ntilde;ol</a></li>
<li id="menu-item-452" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-452" original-class="menu-item menu-item-type-custom menu-item-object-custom menu-item-452"><a href="https://www.apdaparkinson.org/news/">News</a></li>
<li id="menu-item-1523" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1523" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1523"><a href="https://www.apdaparkinson.org/community/northwest/about/contact-us/">Contact</a></li>
<li id="menu-item-454" class="donateBtn menu-item menu-item-type-custom menu-item-object-custom menu-item-454" original-class="donateBtn menu-item menu-item-type-custom menu-item-object-custom menu-item-454"><a target="_blank" href="https://www.apdaparkinson.org/1813d2l">Donate</a></li>
</ul></div>
</div></div>
<nav id="site-navigation" class="main-navigation" original-class="main-navigation" role="navigation"><button class="menu-toggle" original-class="menu-toggle" aria-controls="primary-menu" aria-expanded="false">Menu</button>
<!--mfunc W3TC_DYNAMIC_SECURITY --><div class="menu-main-menu-container" original-class="menu-main-menu-container"><ul id="primary-menu" class="menu apda-menu" original-class="menu apda-menu"><li id="menu-item-378" class="blue menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-378" original-class="blue menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-378" data-menu-content="PGgzPldoYXQgaXMgUGFya2luc29uJ3MgRGlzZWFzZT88L2gzPg0KVGhpcyBzZWN0aW9uIHdpbGwgaGVscCB5b3UgdW5kZXJzdGFuZCB0aGUgYmFzaWNzIG9mIFBhcmtpbnNvbidzIERpc2Vhc2UsIGhvdyBQYXJraW5zb24ncyBEaXNlYXNlIGFmZmVjdHMgdGhlIGJyYWluLCBpdHMgc3ltcHRvbXMgYW5kIG9uZ29pbmcgcmVzZWFyY2guIDxhIGNsYXNzPSJtZW51LWJveC1saW5rIiBocmVmPSJodHRwOi8vd3d3LmFwZGFwYXJraW5zb24ub3JnL3doYXQtaXMtcGFya2luc29ucy8iPkxlYXJuIE1vcmU8L2E+">
<a href="https://www.apdaparkinson.org/what-is-parkinsons/">What is Parkinson&rsquo;s Disease?</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span><div class="menuBox" original-class="menuBox">
<span class="close-mega-menu" original-class="close-mega-menu"><i class="fa fa-times" original-class="fa fa-times" aria-hidden="true"></i></span><ul class="sub-menu" original-class="sub-menu"><li id="menu-item-379" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-379" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-379" data-menu-content="PGgzPldoYXQgQ2F1c2VzIFBhcmtpbnNvbidzPzwvaDM+DQpUaGUgY2F1c2Ugb2YgUGFya2luc29uJ3MgRGlzZWFzZSBpcyBzdGlsbCB1bmtub3duLCBhbHRob3VnaCB0aGVyZSBpcyBzb21lIGV2aWRlbmNlIGZvciB0aGUgcm9sZSBvZiBnZW5ldGljcywgZW52aXJvbm1lbnRhbCBmYWN0b3JzLCBvciBhIGNvbWJpbmF0aW9uIG9mIGJvdGguIEl0IGlzIGFsc28gcG9zc2libGUgdGhhdCB0aGVyZSBtYXkgYmUgbW9yZSB0aGFuIG9uZSBjYXVzZSBvZiBQYXJraW5zb24ncyBEaXNlYXNlIGluY2x1ZGluZyBnZW5ldGljIGZhY3RvcnMsIGVudmlyb25tZW50YWwgZmFjdG9ycywgYW5kIG90aGVyIHJpc2sgZmFjdG9ycy4NCg0KPGEgY2xhc3M9Im1lbnUtYm94LWxpbmsiIGhyZWY9Imh0dHA6Ly93d3cuYXBkYXBhcmtpbnNvbi5vcmcvd2hhdC1pcy1wYXJraW5zb25zL2NhdXNlcy8iPkxlYXJuIE1vcmU8L2E+">
<a href="https://www.apdaparkinson.org/what-is-parkinsons/causes/">Causes of Parkinson&rsquo;s</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-380" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-380" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-380" data-menu-content="PGgzPkRpYWdub3NpbmcgUGFya2luc29uJ3MgRGlzZWFzZTwvaDM+DQpQYXJraW5zb24ncyBEaXNlYXNlIGlzIHVzdWFsbHkgZGlhZ25vc2VkIGNsaW5pY2FsbHksIG1lYW5pbmcgdGhhdCBhIHBoeXNpY2lhbiBsb29rcyBmb3IgdGhlIHByZXNlbmNlIG9yIGFic2VuY2Ugb2YgdGhlIHBvc3NpYmxlIHN5bXB0b21zIG9mIFBhcmtpbnNvbidzIGJ5IGludGVydmlld2luZyB0aGUgcGF0aWVudCBhbmQgcGVyZm9ybWluZyBhIGRldGFpbGVkIG5ldXJvbG9naWMgZXhhbWluYXRpb24uDQoNCjxhIGNsYXNzPSJtZW51LWJveC1saW5rIiBocmVmPSJodHRwOi8vd3d3LmFwZGFwYXJraW5zb24ub3JnL3doYXQtaXMtcGFya2luc29ucy9kaWFnbm9zaW5nLyI+TGVhcm4gTW9yZTwvYT4=">
<a href="https://www.apdaparkinson.org/what-is-parkinsons/diagnosing/">Diagnosing Parkinson&rsquo;s</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-382" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-382" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-382" data-menu-content="PGgzPlN5bXB0b21zIG9mIFBhcmtpbnNvbidzPC9oMz4NCkFsdGhvdWdoIHdlIHByb3ZpZGUgYW4gb3ZlcnZpZXcgb2YgdHlwaWNhbCBzeW1wdG9tcyBvZiBQRCwgcmVtZW1iZXIgdGhleSBjYW4gdmFyeSBncmVhdGx5IGJ5IGluZGl2aWR1YWwgLSBib3RoIGluIHRlcm1zIG9mIHRoZWlyIGludGVuc2l0eSBhbmQgaG93IHRoZXkgcHJvZ3Jlc3MuIE1vdG9yIHN5bXB0b21zIGdlbmVyYWxseSBpbnZvbHZlIG1vdmVtZW50LCB3aGlsZSBub24tbW90b3Igc3ltcHRvbXMgZG8gbm90Lg0KPGg0PkFQREEgSGVhbHRoY2FyZSBDb21tdW5pY2F0aW9uIEdyYXBoPC9oND4NCk5ldyB0b29sISBCeSB1c2luZyB0aGUgQVBEQSBIZWFsdGhjYXJlIENvbW11bmljYXRpb24gR3JhcGggeW91IHdpbGwgYmUgYWJsZSB0byBjb25zaXN0ZW50bHkgdHJhY2sgaW1wb3J0YW50IFBEIHN5bXB0b21zLiBUaGlzIHRvb2wgd2lsbCBhbGxvdyB5b3UgdG8gaWRlbnRpZnkgYW55IGNoYW5nZXMgaW4gc3ltcHRvbXMgYW5kIG1ha2UgdmlzaXRzIHdpdGggeW91ciBoZWFsdGhjYXJlIHByb2Zlc3Npb25hbHMgZm9jdXNlZCBhbmQgcHJvZHVjdGl2ZS4NCg0KPGEgY2xhc3M9Im1lbnUtYm94LWxpbmsiIGhyZWY9Imh0dHA6Ly93d3cuYXBkYXBhcmtpbnNvbi5vcmcvd2hhdC1pcy1wYXJraW5zb25zLyI+TGVhcm4gTW9yZTwvYT4=">
<a href="https://www.apdaparkinson.org/what-is-parkinsons/symptoms/">Symptoms of Parkinson&rsquo;s</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-398" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-398" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-398" data-menu-content="PGgzPlRyZWF0bWVudCAmYW1wOyBNZWRpY2F0aW9uPC9oMz4NCkFsdGhvdWdoIHRoZXJlIGlzIG5vIGN1cmUgZm9yIFBhcmtpbnNvbidzIGF0IHRoaXMgdGltZSwgUGFya2luc29uJ3MgbWVkaWNhdGlvbiwgc3VyZ2ljYWwgb3B0aW9ucywgYW5kIGNvbXBsZW1lbnRhcnkgdGhlcmFwaWVzIHVzZWQgdG8gdHJlYXQgUEQgc3ltcHRvbXMgYXJlIGNvbnRpbnVhbGx5IGltcHJvdmluZy4gVGhpcyBzZWN0aW9uIHByb3ZpZGVzIGFuIG92ZXJ2aWV3IG9mIFBhcmtpbnNvbidzIG1lZGljYXRpb25zLCBkZWVwIGJyYWluIHN0aW11bGF0aW9uLCBjb21wbGVtZW50YXJ5IGFuZCBhbHRlcm5hdGl2ZSBtZWRpY2luZSwgdGhlIGltcG9ydGFudCByb2xlIG9mIGNsaW5pY2FsIHRyaWFscywgYW5kIGFzc2VtYmxpbmcgeW91ciBjYXJlIHRlYW0uDQoNCjxhIGNsYXNzPSJtZW51LWJveC1saW5rIiBocmVmPSJodHRwOi8vd3d3LmFwZGFwYXJraW5zb24ub3JnL3doYXQtaXMtcGFya2luc29ucy90cmVhdG1lbnQtbWVkaWNhdGlvbi8iPkxlYXJuIE1vcmU8L2E+">
<a href="https://www.apdaparkinson.org/what-is-parkinsons/treatment-medication/">Treatment &amp; Medication</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-381" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-381" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-381" data-menu-content="PGgzPkVhcmx5IE9uc2V0IFBhcmtpbnNvbidzIERpc2Vhc2U8L2gzPg0KV2hlbiBzb21lb25lIHdobyBpcyAyMS01MCB5ZWFycyBvbGQgcmVjZWl2ZXMgYSBkaWFnbm9zaXMgb2YgUGFya2luc29uJ3MgZGlzZWFzZSwgaXQgaXMgcmVmZXJyZWQgdG8gYXMgZWFybHkgb25zZXQgUGFya2luc29uJ3MgZGlzZWFzZSwgb3IgeW91bmcgb25zZXQgUGFya2luc29uJ3MgZGlzZWFzZS4gV2hpbGUgc3ltcHRvbXMgYXJlIG1vc3RseSB0aGUgc2FtZSByZWdhcmRsZXNzIG9mIGFnZSwgeW91bmdlciBwZW9wbGUgd2lsbCBleHBlcmllbmNlIHRoZSBkaXNlYXNlIGRpZmZlcmVudGx5IGR1ZSB0byB0aGVpciB1bmlxdWUgbGlmZSBjaXJjdW1zdGFuY2VzLg0KDQo8YSBjbGFzcz0ibWVudS1ib3gtbGluayIgaHJlZj0iaHR0cDovL3d3dy5hcGRhcGFya2luc29uLm9yZy93aGF0LWlzLXBhcmtpbnNvbnMvZWFybHktb25zZXQtcGFya2luc29ucy1kaXNlYXNlLyI+TGVhcm4gTW9yZTwvYT4=">
<a href="https://www.apdaparkinson.org/what-is-parkinsons/early-onset-parkinsons-disease/">Early Onset Parkinson&rsquo;s Disease</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-926" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-926" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-926" data-menu-content="PGgzPkNsaW5pY2FsIFRyaWFsIFBhcnRpY2lwYXRpb248L2gzPg0KQ2xpbmljYWwgdHJpYWxzIGFyZSBhbiBpbXBvcnRhbnQgc3RlcCBpbiBkaXNjb3ZlcmluZyB0aGUgY2F1c2VzLCB0cmVhdG1lbnRzIGFuZCB1bHRpbWF0ZWx5IGEgY3VyZSBmb3IgUGFya2luc29uJ3MuDQoNCjxhIGNsYXNzPSJtZW51LWJveC1saW5rIiBocmVmPSJodHRwOi8vd3d3LmFwZGFwYXJraW5zb24ub3JnL3doYXQtaXMtcGFya2luc29ucy9jbGluaWNhbC10cmlhbHMvIj5MZWFybiBNb3JlPC9hPg==">
<a href="https://www.apdaparkinson.org/resources-support/living-with-parkinsons-disease/clinical-trials/">Clinical Trial Participation</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
</ul><div class="inner-menu-content" original-class="inner-menu-content">
<div>
<h3>What is Parkinson&rsquo;s Disease?</h3>
<p>This section will help you understand the basics of Parkinson&rsquo;s Disease, how Parkinson&rsquo;s Disease affects the brain, its symptoms and ongoing research. <a class="menu-box-link" original-class="menu-box-link" href="http://www.apdaparkinson.org/what-is-parkinsons/">Learn More</a></p>
<div class="css-ss css-ss-wrap" original-class="css-ss css-ss-wrap">
<h4>Share this page:</h4>
<div style="text-align:left;">
<div class="css_single_share_icon_container" original-class="css_single_share_icon_container"><a onclick="window.open(this.href, 'mywin', 'left=50,top=50,width=600,height=350,toolbar=0'); return false;" data-site="" class="css_google_share css_share_link" original-class="css_google_share css_share_link" href="https://plus.google.com/share?url=https://www.apdaparkinson.org/community/northwest/upcoming-events-3/" target="_blank"></a></div>
<div class="css_single_share_icon_container" original-class="css_single_share_icon_container"><a onclick="window.open(this.href, 'mywin', 'left=50,top=50,width=600,height=350,toolbar=0'); return false;" data-site="" class="css_facebook_share css_share_link" original-class="css_facebook_share css_share_link" href="http://www.facebook.com/sharer.php?u=https://www.apdaparkinson.org/community/northwest/upcoming-events-3/" target="_blank"></a></div>
<div class="css_single_share_icon_container" original-class="css_single_share_icon_container"><a onclick="window.open(this.href, 'mywin', 'left=50,top=50,width=600,height=350,toolbar=0'); return false;" data-site="" class="css_twitter_share css_share_link" original-class="css_twitter_share css_share_link" href="http://twitter.com/share?url=https://www.apdaparkinson.org/community/northwest/upcoming-events-3/" target="_blank"></a></div>
</div>
</div>
</div>
<span class="close-mega-menu" original-class="close-mega-menu"><i class="fa fa-times" original-class="fa fa-times" aria-hidden="true"></i></span><li id="menu-item-366" class="light-blue menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-366" original-class="light-blue menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-366" data-menu-content="PGgzPkVkdWNhdGlvbiBhbmQgU3VwcG9ydDwvaDM+DQpXaXRoIHRoZSBsYXJnZXN0IGdyYXNzcm9vdHMgbmV0d29yayBhY3Jvc3MgdGhlIGNvdW50cnksIHRoZSBBbWVyaWNhbiBQYXJraW5zb24gRGlzZWFzZSBBc3NvY2lhdGlvbiAoQVBEQSkgZmVhdHVyZXMgYSBuYXRpb253aWRlIHN5c3RlbSBvZiBDaGFwdGVycyBhbmQgSW5mb3JtYXRpb24gJmFtcDsgUmVmZXJyYWwgKEkmYW1wO1IpIENlbnRlcnMuIExlYXJuIGFib3V0IG91ciBlZHVjYXRpb25hbCBhbmQgc3VwcG9ydCByZXNvdXJjZXMgZm9yIGluZGl2aWR1YWxzIHdpdGggUGFya2luc29uJ3MgYW5kIHRoZWlyIGZhbWlseSBtZW1iZXJzLg0KDQo8YSBjbGFzcz0ibWVudS1ib3gtbGluayIgaHJlZj0iaHR0cHM6Ly93d3cuYXBkYXBhcmtpbnNvbi5vcmcvcmVzb3VyY2VzLXN1cHBvcnQvIj5MZWFybiBNb3JlIGFib3V0IEVkdWNhdGlvbiBhbmQgU3VwcG9ydCBTZXJ2aWNlczwvYT4NCg0KJm5ic3A7">
<a href="https://www.apdaparkinson.org/resources-support/">Education &amp; Support</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span><div class="menuBox" original-class="menuBox">
<span class="close-mega-menu" original-class="close-mega-menu"><i class="fa fa-times" original-class="fa fa-times" aria-hidden="true"></i></span><ul class="sub-menu" original-class="sub-menu"><li id="menu-item-367" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-367" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-367" data-menu-content="PGgzPkxpdmluZyB3aXRoIFBhcmtpbnNvbidzIERpc2Vhc2U8L2gzPg0KT25jZSB5b3UgYXJlIGRpYWdub3NlZCB3aXRoIFBELCB5b3VyIGZvY3VzIHNob3VsZCBiZSBvbiBpbXByb3ZpbmcgeW91ciBzeW1wdG9tcyBhbmQgbWFpbnRhaW5pbmcgYW4gYWN0aXZlIGFuZCBwb3NpdGl2ZSBsaWZlc3R5bGUuIFRoaXMgc2VjdGlvbiBjb3ZlcnMgd2F5cyB0byBtYW5hZ2Ugc3ltcHRvbXMgbGlrZSBlbmdhZ2luZyBpbiByZWd1bGFyIGV4ZXJjaXNlLCBlYXRpbmcgaGVhbHRoeSwgZXhwbG9yaW5nIG1lZGljYXRpb24gYW5kIHRyZWF0bWVudCBvcHRpb25zLCBhbmQgYXNzZW1ibGluZyB5b3VyIGhlYWx0aCBjYXJlIHRlYW0uDQoNCjxhIGNsYXNzPSJtZW51LWJveC1saW5rIiBocmVmPSJodHRwOi8vd3d3LmFwZGFwYXJraW5zb24ub3JnL3Jlc291cmNlcy1zdXBwb3J0L2xpdmluZy13aXRoLXBhcmtpbnNvbnMtZGlzZWFzZS8iPkxlYXJuIE1vcmU8L2E+">
<a href="https://www.apdaparkinson.org/resources-support/living-with-parkinsons-disease/">Living with Parkinson&rsquo;s Disease</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-1950" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1950" original-class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1950" data-menu-content="">
<a href="http://www.apdaparkinson.org/webinar/">Webinar Education Series</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-2604" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2604" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2604" data-menu-content="PGgzPkZpcnN0IFJlc3BvbmRlciBUcmFpbmluZzwvaDM+DQpVbmlxdWUgc3ltcHRvbXMgb2YgUGFya2luc29uJnJzcXVvO3MgY2FuIGJlIG1pc2hhbmRsZWQgYW5kIG1pc3VuZGVyc3Rvb2QgaW4gZW1lcmdlbmN5IHNpdHVhdGlvbnMuIFRoaXMgbmV3IHdlYi1iYXNlZCBwcm9ncmFtIHdpbGwgZWR1Y2F0ZSBwb2xpY2UsIGZpcmVmaWdodGVycyBhbmQgZW1lcmdlbmN5IHNlcnZpY2UgcHJvdmlkZXJzIGFuZCBoZWxwIHNhdmUgbGl2ZXMuDQoNCjxhIGNsYXNzPSJtZW51LWJveC1saW5rIiBocmVmPSJodHRwOi8vd3d3LmFwZGFwYXJraW5zb24ub3JnL3Jlc291cmNlcy1zdXBwb3J0L2ZpcnN0LXJlc3BvbmRlci10cmFpbmluZy8iPkxlYXJuIE1vcmU8L2E+">
<a href="https://www.apdaparkinson.org/resources-support/first-responder-training/">First Responder Training</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-1859" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1859" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1859" data-menu-content="PGgzPlB1YmxpY2F0aW9uczwvaDM+DQpBUERBIHB1Ymxpc2hlcyBtb3JlIHRoYW4gMzAgYnJvY2h1cmVzIGFuZCBwYW1waGxldHMgYXZhaWxhYmxlIGF0IG5vIGNvc3QgdG8gdGhlIHB1YmxpYy4gQVBEQSBmb2N1c2VzIG9uIGRldmVsb3BpbmcgZWR1Y2F0aW9uYWwgbWF0ZXJpYWxzIHRoYXQgYWRkcmVzcyB0aGUgY2xpbmljYWwgYW5kIHBzeWNob3NvY2lhbCBzeW1wdG9tYXRvbG9neSBvZiBQYXJraW5zb24mcnNxdW87cyBkaXNlYXNlIGFuZCBvZmZlciBndWlkYW5jZSBhbmQgaW5mb3JtYXRpb24gZm9yIGNvcGluZyB3aXRoIHRoZSBkaXNlYXNlLiBBbGwgbWF0ZXJpYWxzIGNhbiBiZSBkb3dubG9hZGVkIGFzIFBERnMgb3IgcHJpbnQgY29waWVzIGNhbiBiZSBtYWlsZWQgdG8geW91Lg0KDQo8YSBjbGFzcz0ibWVudS1ib3gtbGluayIgaHJlZj0iaHR0cDovL3d3dy5hcGRhcGFya2luc29uLm9yZy9yZXNvdXJjZXMtc3VwcG9ydC9kb3dubG9hZC1wdWJsaWNhdGlvbnMvIj5MZWFybiBNb3JlPC9hPg==">
<a href="https://www.apdaparkinson.org/resources-support/download-publications/">Publications</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-3406" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3406" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3406" data-menu-content="PGgzPk5ld3NsZXR0ZXIgQXJjaGl2ZTwvaDM+DQpBUERBJ3MgTmV3c2xldHRlciBBcmNoaXZlIGNhbiBoZWxwIHlvdSBmaW5kIGFueSBvZiBvdXIgcGFzdCBuZXdzbGV0dGVycyBkYXRlZCBhbGwgdGhlIHdheSBiYWNrIHRvIDIwMDMuDQoNCjxhIGNsYXNzPSJtZW51LWJveC1saW5rIiBocmVmPSJodHRwczovL3d3dy5hcGRhcGFya2luc29uLm9yZy9uZXdzL25ld3NsZXR0ZXItYXJjaGl2ZS8iPkxlYXJuIE1vcmU8L2E+">
<a href="https://www.apdaparkinson.org/news/newsletter-archive/">Newsletter Archive</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-925" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-925" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-925" data-menu-content="PGgzPkFzayBhIERvY3RvcjwvaDM+DQpVc2Ugb3VyIGNvbnZlbmllbnQgb25saW5lIGZvcm0gdG8gIkFzayBhIERvY3RvciIgeW91ciBxdWVzdGlvbiBvciBjb25jZXJuLiBPdXIgU2NpZW50aWZpYyBhbmQgTWVkaWNhbCBBZmZhaXJzIERlcGFydG1lbnQgY2FuIGhlbHAgeW91IHdpdGggdGhlIGFuc3dlciBhbmQgd2lsbCByZXNwb25kIHVzdWFsbHkgd2l0aGluIG9uZSB3ZWVrLg0KDQo8YSBjbGFzcz0ibWVudS1ib3gtbGluayIgaHJlZj0iaHR0cDovL3d3dy5hcGRhcGFya2luc29uLm9yZy9yZXNvdXJjZXMtc3VwcG9ydC9mb3ItY2FyZWdpdmVycy8iPkxlYXJuIE1vcmU8L2E+">
<a href="https://www.apdaparkinson.org/resources-support/ask-the-doctor/">Ask a Doctor</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-1477" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1477" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1477" data-menu-content="PGgzPkluZm9ybWFjaSZvYWN1dGU7biB5IFJlY3Vyc29zIGVuIEVzcGEmbnRpbGRlO29sPC9oMz4NCkxhIEFtZXJpY2FuIFBhcmtpbnNvbiBEaXNlYXNlIEFzc29jaWF0aW9uIChBUERBIHBvciBzdXMgc2lnbGFzIGVuIGluZ2wmZWFjdXRlO3MpIGZ1ZSBmdW5kYWRhIGVuIGVsIDE5NjEgY29uIGVsIGRvYmxlIHByb3Amb2FjdXRlO3NpdG8gZGUgQWxpdmlhciBsYSBjYXJnYSB5IEVuY29udHJhciBsYSBjdXJhIHBhcmEgZWwgUGFya2luc29uLg0KDQo8YSBjbGFzcz0ibWVudS1ib3gtbGluayIgaHJlZj0iaHR0cDovL3d3dy5hcGRhcGFya2luc29uLm9yZy9yZXNvdXJjZXMtc3VwcG9ydC9lbi1lc3Bhbm9sLyI+QXByZW5kZSBtJmFhY3V0ZTtzPC9hPg==">
<a href="https://www.apdaparkinson.org/resources-support/en-espanol/">En Espa&Atilde;&plusmn;ol</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-951" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-951" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-951" data-menu-content="PGgzPlJlc291cmNlcyBmb3IgVmV0ZXJhbnM8L2gzPg0KVmV0ZXJhbnMgbWF5IGJlIGF0IGFuIGluY3JlYXNlZCByaXNrIG9mIFBhcmtpbnNvbiZyc3F1bztzIGRpc2Vhc2UgKFBEKSBiZWNhdXNlIG9mIHRoZWlyIHNlcnZpY2UuIExlYXJuIG1vcmUgYWJvdXQgcmVzb3VyY2VzIGFuZCBzZXJ2aWNlcyBhdmFpbGFibGUgdG8gdmV0ZXJhbnMgaGVyZS4NCg0KPGEgY2xhc3M9Im1lbnUtYm94LWxpbmsiIGhyZWY9Imh0dHA6Ly93d3cuYXBkYXBhcmtpbnNvbi5vcmcvcmVzb3VyY2VzLXN1cHBvcnQvbmF0aW9uYWwtdmV0ZXJhbi1yZXNvdXJjZXMvIj5MZWFybiBNb3JlPC9hPg==">
<a href="https://www.apdaparkinson.org/resources-support/national-veteran-resources/">Resources for Veterans</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-1070" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1070" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1070" data-menu-content="PGgzPlJlc291cmNlcyBmb3IgQ2FyZSBHaXZlcnM8L2gzPg0KV2hlbiBvbmUgcGVyc29uIGluIGEgY291cGxlIG9yIGZhbWlseSBpcyBhZmZlY3RlZCBieSBQYXJraW5zb24mcnNxdW87cyBkaXNlYXNlLCB0aGUgb3RoZXIgZmFtaWx5IG1lbWJlcnMgbGl2ZSB3aXRoIGl0IGFzIHdlbGwuIExlYXJuIG1vcmUgYWJvdXQgcmVzb3VyY2VzIGFuZCBzdXBwb3J0IGdyb3VwcyBhdmFpbGFibGUgdG8gY2FyZSBnaXZlcnMgaGVyZS4NCg0KPGEgY2xhc3M9Im1lbnUtYm94LWxpbmsiIGhyZWY9Imh0dHA6Ly93d3cuYXBkYXBhcmtpbnNvbi5vcmcvcmVzb3VyY2VzLXN1cHBvcnQvZm9yLWNhcmVnaXZlcnMvIj5MZWFybiBNb3JlPC9hPg==">
<a href="https://www.apdaparkinson.org/resources-support/for-caregivers/">For Care Partners</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-3721" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3721" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3721" data-menu-content="PGgzPlNtYXJ0IFBhdGllbnRzIFBhcmtpbnNvbidzIERpc2Vhc2UgT25saW5lIENvbW11bml0eSBpbiBwYXJ0bmVyc2hpcCB3aXRoIHRoZSBBbWVyaWNhbiBQYXJraW5zb24gRGlzZWFzZSBBc3NvY2lhdGlvbjwvaDM+DQpIZWxwaW5nIHBlb3BsZSB3aXRoIFBhcmtpbnNvbidzIGFuZCB0aGVpciBjYXJlIHBhcnRuZXJzIGNvbm5lY3Qgd2l0aCBlYWNoIG90aGVyIGlzIHRoZSByZWFzb24gdGhlIHdlJ3ZlIGp1c3QgcGFydG5lcmVkIHdpdGggU21hcnQgUGF0aWVudHMgdG8gY3JlYXRlIGEgbmV3IG9ubGluZSBkaXNjdXNzaW9uIGZvcnVtIGZvciBwYXRpZW50cyBhbmQgdGhlaXIgbG92ZWQgb25lcyBkZWFsaW5nIHdpdGggUGFya2luc29uJ3MgRGlzZWFzZS4gTWVtYmVycyBpbiB0aGlzIG9ubGluZSBmb3J1bSBzaGFyZSBoZWxwLCBhZHZpY2UgYW5kIGluZm9ybWF0aW9uIGFib3V0IHRyZWF0bWVudHMsIHN5bXB0b21zIGFuZCBzaWRlIGVmZmVjdHMuDQoNCjxhIGNsYXNzPSJtZW51LWJveC1saW5rIiBocmVmPSJodHRwczovL3d3dy5hcGRhcGFya2luc29uLm9yZy9yZXNvdXJjZXMtc3VwcG9ydC9zbWFydC1wYXRpZW50cy8iPkxlYXJuIE1vcmU8L2E+">
<a href="https://www.apdaparkinson.org/resources-support/smart-patients/">Smart Patients</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-2584" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2584" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2584" data-menu-content="PGgzPk5hdGlvbmFsIFBhcmtpbnNvbidzIFJlaGFiIENlbnRlciBpbiBCb3N0b248L2gzPg0KQVBEQSBOYXRpb25hbCBSZWhhYmlsaXRhdGlvbiBSZXNvdXJjZSBDZW50ZXIgZm9yIFBhcmtpbnNvbiZyc3F1bztzIGRpc2Vhc2UgaXMgbG9jYXRlZCBhdCB0aGUgQm9zdG9uIFVuaXZlcnNpdHkgU2FyZ2VudCBDb2xsZWdlIENlbnRlciBmb3IgTmV1cm9yZWhhYmlsaXRhdGlvbi4gVGhlIENlbnRlciBpcyBhdmFpbGFibGUgdG8gbWVkaWNhbCBwcm9mZXNzaW9uYWxzIGFuZCBwZW9wbGUgd2l0aCBQRCBuYXRpb253aWRlLCBzZXJ2aW5nIGFzIGEgY2VudHJhbCByZXNvdXJjZSBmb3IgaW5mb3JtYXRpb24gYWJvdXQgUEQtcmVsYXRlZCByZWhhYmlsaXRhdGlvbiBhbmQgZXhlcmNpc2UuDQoNCjxhIGNsYXNzPSJtZW51LWJveC1saW5rIiBocmVmPSJodHRwOi8vd3d3LmFwZGFwYXJraW5zb24ub3JnL3Jlc291cmNlcy1zdXBwb3J0L3JlaGFiLXJlc291cmNlLWNlbnRlci8iPkxlYXJuIE1vcmU8L2E+">
<a href="https://www.apdaparkinson.org/resources-support/rehab-resource-center/">National Rehab Center</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
</ul><div class="inner-menu-content" original-class="inner-menu-content">
<div>
<h3>Education and Support</h3>
<p>With the largest grassroots network across the country, the American Parkinson Disease Association (APDA) features a nationwide system of Chapters and Information &amp; Referral (I&amp;R) Centers. Learn about our educational and support resources for individuals with Parkinson&rsquo;s and their family members.</p>
<p><a class="menu-box-link" original-class="menu-box-link" href="https://www.apdaparkinson.org/resources-support/">Learn More about Education and Support Services</a></p>
<p>&nbsp;</p>
<div class="css-ss css-ss-wrap" original-class="css-ss css-ss-wrap">
<h4>Share this page:</h4>
<div style="text-align:left;">
<div class="css_single_share_icon_container" original-class="css_single_share_icon_container"><a onclick="window.open(this.href, 'mywin', 'left=50,top=50,width=600,height=350,toolbar=0'); return false;" data-site="" class="css_google_share css_share_link" original-class="css_google_share css_share_link" href="https://plus.google.com/share?url=https://www.apdaparkinson.org/community/northwest/upcoming-events-3/" target="_blank"></a></div>
<div class="css_single_share_icon_container" original-class="css_single_share_icon_container"><a onclick="window.open(this.href, 'mywin', 'left=50,top=50,width=600,height=350,toolbar=0'); return false;" data-site="" class="css_facebook_share css_share_link" original-class="css_facebook_share css_share_link" href="http://www.facebook.com/sharer.php?u=https://www.apdaparkinson.org/community/northwest/upcoming-events-3/" target="_blank"></a></div>
<div class="css_single_share_icon_container" original-class="css_single_share_icon_container"><a onclick="window.open(this.href, 'mywin', 'left=50,top=50,width=600,height=350,toolbar=0'); return false;" data-site="" class="css_twitter_share css_share_link" original-class="css_twitter_share css_share_link" href="http://twitter.com/share?url=https://www.apdaparkinson.org/community/northwest/upcoming-events-3/" target="_blank"></a></div>
</div>
</div>
</div>
<span class="close-mega-menu" original-class="close-mega-menu"><i class="fa fa-times" original-class="fa fa-times" aria-hidden="true"></i></span><li id="menu-item-458" class="light-green menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-458" original-class="light-green menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-458" data-menu-content="PGgzPlJlc2VhcmNoPC9oMz4NCldlIGFyZSBjb21taXR0ZWQgdG8gc2NpZW50aWZpYyByZXNlYXJjaCBhbmQgaGF2ZSBiZWVuIGEgZnVuZGluZyBwYXJ0bmVyIGluIG1vc3QgbWFqb3IgUGFya2luc29uJ3MgZGlzZWFzZSBzY2llbnRpZmljIGJyZWFrdGhyb3VnaHMsIGludmVzdGluZyBtb3JlIHRoYW4gJDQ2IG1pbGxpb24gaW4gcmVzZWFyY2ggc2luY2UgMTk2MS4gUmVhZCBhYm91dCB3aGF0IHdlIGZ1bmQgYW5kIGV4cGxvcmUgb3Bwb3J0dW5pdGllcyBmb3IgZnVuZGluZy4NCjxhIGNsYXNzPSJtZW51LWJveC1saW5rIiBocmVmPSJodHRwOi8vd3d3LmFwZGFwYXJraW5zb24ub3JnL3Jlc2VhcmNoLyI+TGVhcm4gTW9yZTwvYT4=">
<a href="https://www.apdaparkinson.org/research/">Research</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span><div class="menuBox" original-class="menuBox">
<span class="close-mega-menu" original-class="close-mega-menu"><i class="fa fa-times" original-class="fa fa-times" aria-hidden="true"></i></span>
<ul class="sub-menu" original-class="sub-menu"><li id="menu-item-927" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-927" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-927" data-menu-content="PGgzPldoYXQgV2UgRnVuZDwvaDM+DQpBUERBIGhhcyBiZWVuIGEgZnVuZGluZyBwYXJ0bmVyIGluIG1vc3QgbWFqb3Igc2NpZW50aWZpYyBicmVha3Rocm91Z2hzIGFuZCBoYXMgYXdhcmRlZCBtb3JlIHRoYW4gJDQ2IG1pbGxpb24gaW4gcmVzZWFyY2ggZ3JhbnRzIHRvIGRhdGUuDQo8YSBjbGFzcz0ibWVudS1ib3gtbGluayIgc3R5bGU9Im1hcmdpbi1sZWZ0OiAyNTBweDsiIGhyZWY9Imh0dHA6Ly93d3cuYXBkYXBhcmtpbnNvbi5vcmcvcmVzZWFyY2gvd2hhdC13ZS1mdW5kIj5MZWFybiBNb3JlPC9hPg==">
<a href="https://www.apdaparkinson.org/research/what-we-fund/">What We Fund</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-928" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-928" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-928" data-menu-content="PGgzPlJlc2VhcmNoIE9wcG9ydHVuaXRpZXM8L2gzPg0KQVBEQSBpcyBjb21taXR0ZWQgdG8gc2NpZW50aWZpYyByZXNlYXJjaCBhbmQgaGF2ZSBiZWVuIGEgZnVuZGluZyBwYXJ0bmVyIGluIG1vc3QgbWFqb3IgUGFya2luc29uJ3MgZGlzZWFzZSBzY2llbnRpZmljIGJyZWFrdGhyb3VnaHMsIGludmVzdGluZyBtb3JlIHRoYW4gJDE3MCBtaWxsaW9uIGluIHJlc2VhcmNoIHNpbmNlIDE5NjEuIFJlYWQgYWJvdXQgd2hhdCB3ZSBmdW5kIGFuZCBleHBsb3JlIG9wcG9ydHVuaXRpZXMgZm9yIGZ1bmRpbmcuDQo8YSBjbGFzcz0ibWVudS1ib3gtbGluayIgc3R5bGU9Im1hcmdpbi1sZWZ0OiAyNTBweDsiIGhyZWY9Imh0dHA6Ly93d3cuYXBkYXBhcmtpbnNvbi5vcmcvcmVzZWFyY2gvcmVzZWFyY2gtb3Bwb3J0dW50aWVzIj5MZWFybiBNb3JlPC9hPg==">
<a href="https://www.apdaparkinson.org/research/research-opportunities/">Research Opportunities</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-2917" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2917" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2917" data-menu-content="PGgzPkNlbnRlcnMgZm9yIEFkdmFuY2VkIFJlc2VhcmNoPC9oMz4NClRoZSBDZW50ZXJzIHN1cHBvcnQgbGFyZ2UgcmVzZWFyY2ggcHJvZ3JhbXMgYW5kIGZhY2lsaXRhdGUgZGlzY292ZXJ5IGF0IHRoZSBmb3JlZnJvbnQgb2YgaW52ZXN0aWdhdGlvbnMgaW4gdGhlIGNhdXNlcywgdHJlYXRtZW50cyBhbmQgdWx0aW1hdGVseSBmaW5kaW5nIHRoZSBjdXJlKHMpIGZvciBQYXJraW5zb24ncyBkaXNlYXNlLg0KDQo8YSBjbGFzcz0ibWVudS1ib3gtbGluayIgc3R5bGU9Im1hcmdpbi1sZWZ0OiAyNTBweDsiIGhyZWY9Imh0dHBzOi8vd3d3LmFwZGFwYXJraW5zb24ub3JnL3Jlc2VhcmNoL2FkdmFuY2VkLWNlbnRlcnMvIj5MZWFybiBNb3JlPC9hPg==">
<a href="https://www.apdaparkinson.org/research/advanced-centers/">Centers for Advanced Research</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
</ul><div class="inner-menu-content" original-class="inner-menu-content">
<div>
<h3>Research</h3>
<p>We are committed to scientific research and have been a funding partner in most major Parkinson&rsquo;s disease scientific breakthroughs, investing more than $46 million in research since 1961. Read about what we fund and explore opportunities for funding.<br><a class="menu-box-link" original-class="menu-box-link" href="http://www.apdaparkinson.org/research/">Learn More</a></p>
<div class="css-ss css-ss-wrap" original-class="css-ss css-ss-wrap">
<h4>Share this page:</h4>
<div style="text-align:left;">
<div class="css_single_share_icon_container" original-class="css_single_share_icon_container"><a onclick="window.open(this.href, 'mywin', 'left=50,top=50,width=600,height=350,toolbar=0'); return false;" data-site="" class="css_google_share css_share_link" original-class="css_google_share css_share_link" href="https://plus.google.com/share?url=https://www.apdaparkinson.org/community/northwest/upcoming-events-3/" target="_blank"></a></div>
<div class="css_single_share_icon_container" original-class="css_single_share_icon_container"><a onclick="window.open(this.href, 'mywin', 'left=50,top=50,width=600,height=350,toolbar=0'); return false;" data-site="" class="css_facebook_share css_share_link" original-class="css_facebook_share css_share_link" href="http://www.facebook.com/sharer.php?u=https://www.apdaparkinson.org/community/northwest/upcoming-events-3/" target="_blank"></a></div>
<div class="css_single_share_icon_container" original-class="css_single_share_icon_container"><a onclick="window.open(this.href, 'mywin', 'left=50,top=50,width=600,height=350,toolbar=0'); return false;" data-site="" class="css_twitter_share css_share_link" original-class="css_twitter_share css_share_link" href="http://twitter.com/share?url=https://www.apdaparkinson.org/community/northwest/upcoming-events-3/" target="_blank"></a></div>
</div>
</div>
</div>
<span class="close-mega-menu" original-class="close-mega-menu"><i class="fa fa-times" original-class="fa fa-times" aria-hidden="true"></i></span><li id="menu-item-363" class="purple menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-363" original-class="purple menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-363" data-menu-content="PGgzPkdldCBJbnZvbHZlZDwvaDM+DQpBcyB0aGUgY291bnRyeSdzIGxhcmdlc3QgZ3Jhc3Nyb290cyBQYXJraW5zb24ncyBvcmdhbml6YXRpb24sIHdlIHJlbHkgb24gdGhlIGNvbW11bml0eSB0byBoZWxwIHVzIGluIG91ciBjYXVzZS4gSm9pbiBvdXIgY29tbXVuaXR5IHRvZGF5Lg0KDQo8YSBjbGFzcz0ibWVudS1ib3gtbGluayIgaHJlZj0iaHR0cDovL3d3dy5hcGRhcGFya2luc29uLm9yZy9nZXQtaW52b2x2ZWQvIj5MZWFybiBNb3JlPC9hPg==">
<a href="https://www.apdaparkinson.org/get-involved/">Get Involved</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span><div class="menuBox" original-class="menuBox">
<span class="close-mega-menu" original-class="close-mega-menu"><i class="fa fa-times" original-class="fa fa-times" aria-hidden="true"></i></span><ul class="sub-menu" original-class="sub-menu"><!-----------------<li id="menu-item-18" class="menu-item menu-item-type-post_type menu-item-object-chapter menu-item-18" original-class="menu-item menu-item-type-post_type menu-item-object-chapter menu-item-18" data-menu-content="">
<a href="https://www.apdaparkinson.org/community/northwest/">Northwest</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>----------------------------><li id="menu-item-1297" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1297" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1297" data-menu-content="PGgzPldheXMgdG8gR2l2ZTwvaDM+DQpXZSBpbnZpdGUgeW91IHRvIHBhcnRuZXIgd2l0aCBBUERBIHRvIHByb3ZpZGUgbXVjaCBuZWVkZWQgc3VwcG9ydCB0aGF0IGNhbiBoZWxwIGltcHJvdmUgdGhlIHF1YWxpdHkgb2YgbGlmZSBmb3IgdGhlIDEsMDAwLDAwMCsgaW5kaXZpZHVhbHMgbGl2aW5nIHdpdGggUGFya2luc29uJ3MgZGlzZWFzZSBpbiB0aGUgVVMuDQoNCjxhIGNsYXNzPSJtZW51LWJveC1saW5rIiBocmVmPSJodHRwOi8vd3d3LmFwZGFwYXJraW5zb24ub3JnL2dldC1pbnZvbHZlZC93YXlzLXRvLWdpdmUvIj5MZWFybiBNb3JlPC9hPg==">
<a href="https://www.apdaparkinson.org/get-involved/ways-to-give/">Ways to Give</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-939" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-939" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-939" data-menu-content="PGgzPldhbGsgd2l0aCB1cyE8L2gzPg0KPGltZyBjbGFzcz0iYWxpZ25yaWdodCIgc3R5bGU9InBhZGRpbmc6IDFlbTsiIHNyYz0iaHR0cDovL3d3dy5hcGRhcGFya2luc29uLm9yZy93cC1jb250ZW50L3VwbG9hZHMvMjAxNy8wMi9BUERBX09wdGltaXNtV2Fsa19Mb2dvX1JHQl9zbS5wbmciIHdpZHRoPSIzMDAiIC8+PHN0cm9uZz5TdHJlbmd0aCBpbiBvcHRpbWlzbS4gSG9wZSBpbiBwcm9ncmVzcy48L3N0cm9uZz4NClRoZSBPcHRpbWlzbSBXYWxrIGlzIHBhcnQgb2YgYSBuYXRpb253aWRlIG1vdmVtZW50IHRvIG1vYmlsaXplIGFuZCBpbnNwaXJlIHBlb3BsZSB0byBzdGVwIHVwIGFuZCBoZWxwIHB1dCBhbiBlbmQgdG8gUGFya2luc29uJ3MgZGlzZWFzZS4gSm9pbiB1cywgZmluZCBhbiBldmVudCBuZWFyIHlvdSENCg0KPGEgY2xhc3M9Im1lbnUtYm94LWxpbmsiIGhyZWY9Imh0dHA6Ly93d3cuYXBkYXBhcmtpbnNvbi5vcmcvZ2V0LWludm9sdmVkL29wdGltaXNtLXdhbGtzLyI+TGVhcm4gTW9yZTwvYT4=">
<a href="https://www.apdaparkinson.org/get-involved/optimism-walks/">Optimism Walk</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-2763" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2763" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2763" data-menu-content="PGgzPkNvcnBvcmF0ZSBQYXJ0bmVycyAmYW1wOyBDby1WZW50dXJlczwvaDM+DQpUaGUgQW1lcmljYW4gUGFya2luc29uIERpc2Vhc2UgQXNzb2NpYXRpb24gKEFQREEpIGdyZWF0bHkgdmFsdWVzIHN0cmF0ZWdpYyBhbGxpYW5jZXMgdGhhdCBicmluZyBncmVhdGVyIGF3YXJlbmVzcyBhbmQgZnVuZHMgdG8gcHJvdmlkZSBzdXBwb3J0LCBlZHVjYXRpb24gYW5kIHJlc2VhcmNoIHRoYXQgd2lsbCBoZWxwIGV2ZXJ5b25lIGltcGFjdGVkIGJ5IFBhcmtpbnNvbiZyc3F1bztzIGRpc2Vhc2UgbGl2ZSBsaWZlIHRvIHRoZSBmdWxsZXN0LiBBUERBIGlzIGdyYXRlZnVsIHRoYXQgc28gbWFueSBzaGFyZSBvdXIgY29tbWl0bWVudCBhbmQgZGV0ZXJtaW5hdGlvbiB0byBjaGFuZ2UgbGl2ZXMgZm9yIHRoZSBiZXR0ZXIuDQoNCjxhIGNsYXNzPSJtZW51LWJveC1saW5rIiBocmVmPSJodHRwczovL3d3dy5hcGRhcGFya2luc29uLm9yZy9nZXQtaW52b2x2ZWQvcGFydG5lcnMtY28tdmVudHVyZS8iPkxlYXJuIE1vcmU8L2E+">
<a href="https://www.apdaparkinson.org/get-involved/partners-co-venture/">Corporate Partnerships</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-364" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-364" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-364" data-menu-content="PGgzPkluc3BpcmUgT3RoZXJzPC9oMz4NClNoYXJlIHlvdXIgc3RvcnkgYW5kIGluc3BpcmUgb3RoZXJzLg0KDQo8YSBjbGFzcz0ibWVudS1ib3gtbGluayIgaHJlZj0iaHR0cDovL3d3dy5hcGRhcGFya2luc29uLm9yZy9nZXQtaW52b2x2ZWQvc2hhcmUteW91ci1zdG9yeS8iPlNoYXJlPC9hPg==">
<a href="https://www.apdaparkinson.org/get-involved/share-your-story/">Share Your Story</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-3444" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3444" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3444" data-menu-content="PGgzPlNob3AgdG8gU3VwcG9ydCBBUERBPC9oMz4NCldobyBrbmV3IGRvbmF0aW5nIGNvdWxkIGJlIHRoaXMgc2ltcGxlPyBWaXNpdCBBUERBJ3MmbmJzcDtzaG9wcGluZyBzaXRlIHdpdGggb3ZlciAxLDIwMCBzdG9yZXMgdG8gY2hvb3NlIGZyb20hIFVwIHRvIDEwJSBvZiB5b3VyIHB1cmNoYXNlIGhlbHBzIEFQREEgcHJvdmlkZSB0aGUgc3VwcG9ydCwgc2VydmljZXMsIGFuZCByZXNlYXJjaCB0aGF0IHdpbGwgaGVscCBldmVyeW9uZSBpbXBhY3RlZCBieSBQYXJraW5zb24ncyZuYnNwO2Rpc2Vhc2UgbGl2ZSBsaWZlIHRvIHRoZSBmdWxsZXN0LiZuYnNwO1NhbWUgZ3JlYXQgc3RvcmVzLCBzYW1lIGdyZWF0IGRlYWxzLCBhbmQgYSBjaGFuY2UgdG8gc3VwcG9ydCA8c3Ryb25nPmF0IG5vIGV4dHJhIGNvc3QhPC9zdHJvbmc+DQoNCjxhIGNsYXNzPSJtZW51LWJveC1saW5rIiBocmVmPSJodHRwczovL3d3dy5hcGRhcGFya2luc29uLm9yZy9nZXQtaW52b2x2ZWQvd2F5cy10by1naXZlL3Nob3Atc3VwcG9ydC1hcGRhLyI+TGVhcm4gTW9yZTwvYT4=">
<a href="https://www.apdaparkinson.org/get-involved/ways-to-give/shop-support-apda/">Shop to Support APDA</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-1949" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1949" original-class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1949" data-menu-content="">
<a href="http://www.apdaparkinson.org/story/">Stories of Optimism</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-1312" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1312" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1312" data-menu-content="PGgzPkRvLUl0LVlvdXJzZWxmJm5ic3A7RnVuZHJhaXNpbmc8L2gzPg0KV2UgaW52aXRlIHlvdSB0byBwYXJ0bmVyIHdpdGggQVBEQSB0byBwcm92aWRlIG11Y2ggbmVlZGVkIHN1cHBvcnQgdGhhdCBjYW4gaGVscCBpbXByb3ZlIHRoZSBxdWFsaXR5IG9mIGxpZmUgZm9yIHRoZSAxLDAwMCwwMDArIGluZGl2aWR1YWxzIGxpdmluZyB3aXRoIFBhcmtpbnNvbidzIGRpc2Vhc2UgaW4gdGhlIFVTLiBUaGlzIHBhZ2UgcHJvdmlkZXMgaW5mb3JtYXRpb24gYWJvdXQgam9pbmluZyBleGlzdGluZyBldmVudHMsIGNyZWF0aW5nIHlvdXIgb3duIGNhbXBhaWduLCBhbmQgc3RhcnRpbmcgY29tbXVuaXR5IGV2ZW50cy4NCg0KPGEgY2xhc3M9Im1lbnUtYm94LWxpbmsiIGhyZWY9Imh0dHA6Ly93d3cuYXBkYXBhcmtpbnNvbi5vcmcvZ2V0LWludm9sdmVkL2RpeS1mdW5kcmFpc2luZy8iPkxlYXJuIE1vcmU8L2E+">
<a href="https://www.apdaparkinson.org/get-involved/diy-fundraising/">Do-It-Yourself Fundraising</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
</ul><div class="inner-menu-content" original-class="inner-menu-content">
<div>
<h3>Get Involved</h3>
<p>As the country&rsquo;s largest grassroots Parkinson&rsquo;s organization, we rely on the community to help us in our cause. Join our community today.</p>
<p><a class="menu-box-link" original-class="menu-box-link" href="http://www.apdaparkinson.org/get-involved/">Learn More</a></p>
<div class="css-ss css-ss-wrap" original-class="css-ss css-ss-wrap">
<h4>Share this page:</h4>
<div style="text-align:left;">
<div class="css_single_share_icon_container" original-class="css_single_share_icon_container"><a onclick="window.open(this.href, 'mywin', 'left=50,top=50,width=600,height=350,toolbar=0'); return false;" data-site="" class="css_google_share css_share_link" original-class="css_google_share css_share_link" href="https://plus.google.com/share?url=https://www.apdaparkinson.org/community/northwest/upcoming-events-3/" target="_blank"></a></div>
<div class="css_single_share_icon_container" original-class="css_single_share_icon_container"><a onclick="window.open(this.href, 'mywin', 'left=50,top=50,width=600,height=350,toolbar=0'); return false;" data-site="" class="css_facebook_share css_share_link" original-class="css_facebook_share css_share_link" href="http://www.facebook.com/sharer.php?u=https://www.apdaparkinson.org/community/northwest/upcoming-events-3/" target="_blank"></a></div>
<div class="css_single_share_icon_container" original-class="css_single_share_icon_container"><a onclick="window.open(this.href, 'mywin', 'left=50,top=50,width=600,height=350,toolbar=0'); return false;" data-site="" class="css_twitter_share css_share_link" original-class="css_twitter_share css_share_link" href="http://twitter.com/share?url=https://www.apdaparkinson.org/community/northwest/upcoming-events-3/" target="_blank"></a></div>
</div>
</div>
</div>
<span class="close-mega-menu" original-class="close-mega-menu"><i class="fa fa-times" original-class="fa fa-times" aria-hidden="true"></i></span><li id="menu-item-8498" class="menu-item menu-item-type-post_type menu-item-object-chapter menu-item-has-children menu-item-8498" original-class="menu-item menu-item-type-post_type menu-item-object-chapter menu-item-has-children menu-item-8498" data-menu-content="PGgzPkFQREEgTm9ydGh3ZXN0IENoYXB0ZXI8L2gzPg0KUHJvdmlkaW5nIHJlc291cmNlcyB0byBBbGFza2EsIElkYWhvLCBNb250YW5hLCBPcmVnb24gYW5kIFdhc2hpbmd0b24gc3RhdGVzLCBBUERBIE5vcnRod2VzdCBhaW1zIHRvIGZ1bGZpbGwgb3VyIG1pc3Npb24gYnkgZWR1Y2F0aW5nIGFuZCBlbXBvd2VyaW5nIHRob3NlIGluIG91ciBjb21tdW5pdHkgY2hhbGxlbmdlZCB3aXRoIFBhcmtpbnNvbiZyc3F1bztzIGJ5IHByb21vdGluZyBob3BlIGFuZCBvcHRpbWlzbSB0aHJvdWdoIGlubm92YXRpdmUgc2VydmljZXMgYW5kIHByb2dyYW1zLCBhbmQgZnVuZGluZyB2aXRhbCBsb2NhbCBhbmQgbmF0aW9uYWwgcmVzZWFyY2guDQoNCjxhIGNsYXNzPSJtZW51LWJveC1saW5rIiBocmVmPSJodHRwczovL3d3dy5hcGRhcGFya2luc29uLm9yZy9jb21tdW5pdHkvbm9ydGh3ZXN0LyI+TGVhcm4gTW9yZTwvYT4=">
<a href="https://www.apdaparkinson.org/community/">APDA in Your Community</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span><div class="menuBox" original-class="menuBox">
<span class="close-mega-menu" original-class="close-mega-menu"><i class="fa fa-times" original-class="fa fa-times" aria-hidden="true"></i></span>
<!---XX----------------------------------------------------------------------------<ul class="sub-menu" original-class="sub-menu">
<li id="menu-item-8507" class="menu-item menu-item-type-post_type menu-item-object-chapter-content-page menu-item-8507" original-class="menu-item menu-item-type-post_type menu-item-object-chapter-content-page menu-item-8507" data-menu-content="PGgyPjIwMTcgT3B0aW1pc20gV2FsazwvaDI+DQo8aDM+U3VuZGF5LCBKdW5lIDQsIDIwMTc8L2gzPg0KPHAgY2xhc3M9InR4dGxlZnQiPlNoaXAgQ2FuYWwgVHJhaWwNClN0YXJ0IGF0IE5pY2tlcnNvbiBTdHJlZXQgU2Fsb29uLCAzMTggTmlja2Vyc29uIFN0cmVldA0KU2VhdHRsZSwgV0E8L3A+DQo8YSBocmVmPSJodHRwOi8vYXBkYXBhcmtpbnNvbi5kb25vcmRyaXZlLmNvbS9pbmRleC5jZm0/ZnVzZWFjdGlvbj1kb25vckRyaXZlLmV2ZW50JiMwMzg7ZXZlbnRJRD04NDIiIGNsYXNzPSJhcGRhLWJ1dHRvbiBjb2xvci1wdXJwbGUiPjxzcGFuPlJlZ2lzdGVyPC9zcGFuPjwvYT4=">
<a href="https://www.apdaparkinson.org/community/northwest/upcoming-events-3/">Chapter Events &amp; Programs</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-8508" class="menu-item menu-item-type-post_type menu-item-object-chapter-content-page menu-item-8508" original-class="menu-item menu-item-type-post_type menu-item-object-chapter-content-page menu-item-8508" data-menu-content="">
<a href="https://www.apdaparkinson.org/community/northwest/resources-support/">Local Resources &amp; Support</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-8509" class="menu-item menu-item-type-post_type menu-item-object-chapter-content-page menu-item-8509" original-class="menu-item menu-item-type-post_type menu-item-object-chapter-content-page menu-item-8509" data-menu-content="">
<a href="https://www.apdaparkinson.org/community/northwest/ways-donate-nw/">Ways to Give</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
<li id="menu-item-8510" class="menu-item menu-item-type-post_type menu-item-object-chapter-content-page menu-item-8510" original-class="menu-item menu-item-type-post_type menu-item-object-chapter-content-page menu-item-8510" data-menu-content="">
<a href="https://www.apdaparkinson.org/community/northwest/about/">About APDA Northwest</a><span class="menu-dropdown-button" original-class="menu-dropdown-button"><i class="fa fa-caret-down" original-class="fa fa-caret-down" aria-hidden="true"></i></span>
</li>
</ul>---------------------------------------------------------------------------------------------------------------------------------->
<div class="inner-menu-content" original-class="inner-menu-content">
<div>
<h3>APDA in Your Community</h3>
<p>The American Parkinson Disease Association nationwide network provides information and referral, education and support programs, health and wellness activities, and events to facilitate a better quality of life for the Parkinson's community. It is this grassroots structure that distinguishes APDA from other organizations serving people with Parkinson's disease.</p>
<p><a class="menu-box-link" original-class="menu-box-link" href="https://www.apdaparkinson.org/community/">Learn More</a></p>
<div class="css-ss css-ss-wrap" original-class="css-ss css-ss-wrap">
<h4>Share this page:</h4>
<div style="text-align:left;">
<div class="css_single_share_icon_container" original-class="css_single_share_icon_container"><a onclick="window.open(this.href, 'mywin', 'left=50,top=50,width=600,height=350,toolbar=0'); return false;" data-site="" class="css_google_share css_share_link" original-class="css_google_share css_share_link" href="https://plus.google.com/share?url=https://www.apdaparkinson.org/community/northwest/upcoming-events-3/" target="_blank"></a></div>
<div class="css_single_share_icon_container" original-class="css_single_share_icon_container"><a onclick="window.open(this.href, 'mywin', 'left=50,top=50,width=600,height=350,toolbar=0'); return false;" data-site="" class="css_facebook_share css_share_link" original-class="css_facebook_share css_share_link" href="http://www.facebook.com/sharer.php?u=https://www.apdaparkinson.org/community/northwest/upcoming-events-3/" target="_blank"></a></div>
<div class="css_single_share_icon_container" original-class="css_single_share_icon_container"><a onclick="window.open(this.href, 'mywin', 'left=50,top=50,width=600,height=350,toolbar=0'); return false;" data-site="" class="css_twitter_share css_share_link" original-class="css_twitter_share css_share_link" href="http://twitter.com/share?url=https://www.apdaparkinson.org/community/northwest/upcoming-events-3/" target="_blank"></a></div>
</div>
</div>
</div>
<span class="close-mega-menu" original-class="close-mega-menu"><i class="fa fa-times" original-class="fa fa-times" aria-hidden="true"></i></span><li id="menu-item-search-parent" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children" original-class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children">
<a class="menu-search-hover" original-class="menu-search-hover" href="https://www.apdaparkinson.org/community/northwest/upcoming-events-3/"><i class="fa fa-search" original-class="fa fa-search" aria-hidden="true"></i></a><div class="menuBox" original-class="menuBox"><div class="inner-menu-content" original-class="inner-menu-content" id="menu-item-inlinesearch"><form method="get" class="menu-search-form" original-class="menu-search-form" action="https://www.apdaparkinson.org/">
<input class="text_input" original-class="text_input" type="text" value="Enter Text &amp; Click to Search" name="s" id="s" onfocus="if (this.value == 'Enter Text &amp; Click to Search') {this.value = '';}" onblur="if (this.value == '') {this.value = 'Enter Text &amp; Click to Search';}"><input type="submit" class="my-wp-search" original-class="my-wp-search" id="searchsubmit" value="search"></form></div></div>
</li>
</div> <!--/mfunc W3TC_DYNAMIC_SECURITY -->
<div id="content" class="site-content" original-class="site-content">
<div id="primary" class="content-area" original-class="content-area">
<main id="main" class="site-main" original-class="site-main" role="main"><p id="breadcrumbs"><span xmlns:v="http://rdf.data-vocabulary.org/#"><span typeof="v:Breadcrumb"><a href="https://www.apdaparkinson.org/" rel="v:url" property="v:title"><i class="fa fa-home bigger" original-class="fa fa-home bigger"></i></a> <i class="fa fa-chevron-right" original-class="fa fa-chevron-right"></i> 
<!----------<span rel="v:child" typeof="v:Breadcrumb"><a href="https://www.apdaparkinson.org/community/northwest/" rel="v:url" property="v:title">Northwest</a> <i class="fa fa-chevron-right" original-class="fa fa-chevron-right"></i>---->
<span class="breadcrumb_last" original-class="breadcrumb_last">Planned Giving</span></span></span><span style="float:right;" class="font-resize" original-class="font-resize"><span class="fr-a-icon" original-class="fr-a-icon"><img src="/sites/all/themes/apdaparkinson/img/big-little-a.png"></span><span class="increase-font-smaller" original-class="increase-font-smaller"><img src="/sites/all/themes/apdaparkinson/img/font-minus.svg"></span><span class="increase-font-larger" original-class="increase-font-larger"><img src="/sites/all/themes/apdaparkinson/img/font-plus.svg"></span></span></p>
<article id="post-1625" class="post-1625 chapter-content-page type-chapter-content-page status-publish has-post-thumbnail hentry" original-class="post-1625 chapter-content-page type-chapter-content-page status-publish has-post-thumbnail hentry"><header class="entry-header has-featured" original-class="entry-header has-featured"><div class="wrapper" original-class="wrapper"><h1 class="entry-title" original-class="entry-title">Ways to Give</h1></div>
</header><aside id="chapter-top-hero"></aside><div id="chapter-image-menu" style="display:none;"><div class="wrapper" original-class="wrapper">
<div class="featured-text" original-class="featured-text">Join our Community</div>
<ul class="chapter-sub-menu" original-class="chapter-sub-menu"><li><a href="https://www.apdaparkinson.org/community/northwest/upcoming-events-3/"><img width="150" height="150" src="/sites/all/themes/apdaparkinson/img/calendar-white-150x150.png" class="attachment-thumbnail size-thumbnail wp-post-image" original-class="attachment-thumbnail size-thumbnail wp-post-image" alt="" srcset="/sites/all/themes/apdaparkinson/img/calendar-white-150x150.png 150w, https://d2icp22po6iej.cloudfront.net/wp-content/uploads/2017/02/calendar-white-300x300.png 300w, https://d2icp22po6iej.cloudfront.net/wp-content/uploads/2017/02/calendar-white-768x768.png 768w, https://d2icp22po6iej.cloudfront.net/wp-content/uploads/2017/02/calendar-white-1024x1024.png 1024w, https://d2icp22po6iej.cloudfront.net/wp-content/uploads/2017/02/calendar-white.png 1200w" sizes="(max-width: 150px) 100vw, 150px"></a></li>
<li><a href="https://www.apdaparkinson.org/community/northwest/resources-support/"><img width="150" height="150" src="/sites/all/themes/apdaparkinson/img/info-150x150.png" class="attachment-thumbnail size-thumbnail wp-post-image" original-class="attachment-thumbnail size-thumbnail wp-post-image" alt="" srcset="/sites/all/themes/apdaparkinson/img/info-150x150.png 150w, https://d2icp22po6iej.cloudfront.net/wp-content/uploads/2017/02/info-300x300.png 300w, https://d2icp22po6iej.cloudfront.net/wp-content/uploads/2017/02/info-768x768.png 768w, https://d2icp22po6iej.cloudfront.net/wp-content/uploads/2017/02/info-1024x1024.png 1024w, https://d2icp22po6iej.cloudfront.net/wp-content/uploads/2017/02/info.png 1200w" sizes="(max-width: 150px) 100vw, 150px"></a></li>
<li><a href="https://www.apdaparkinson.org/community/northwest/ways-donate-nw/"><img width="150" height="150" src="/sites/all/themes/apdaparkinson/img/ways-to-give-150x150.png" class="attachment-thumbnail size-thumbnail wp-post-image" original-class="attachment-thumbnail size-thumbnail wp-post-image" alt="" srcset="/sites/all/themes/apdaparkinson/img/ways-to-give-150x150.png 150w, https://d2icp22po6iej.cloudfront.net/wp-content/uploads/2017/02/ways-to-give-300x300.png 300w, https://d2icp22po6iej.cloudfront.net/wp-content/uploads/2017/02/ways-to-give-768x768.png 768w, https://d2icp22po6iej.cloudfront.net/wp-content/uploads/2017/02/ways-to-give-1024x1024.png 1024w, https://d2icp22po6iej.cloudfront.net/wp-content/uploads/2017/02/ways-to-give.png 1200w" sizes="(max-width: 150px) 100vw, 150px"></a></li>
<li><a href="https://www.apdaparkinson.org/community/northwest/about/"><img width="150" height="150" src="/sites/all/themes/apdaparkinson/img/about-chapter-150x150.png" class="attachment-thumbnail size-thumbnail wp-post-image" original-class="attachment-thumbnail size-thumbnail wp-post-image" alt="" srcset="/sites/all/themes/apdaparkinson/img/about-chapter-150x150.png 150w, https://d2icp22po6iej.cloudfront.net/wp-content/uploads/2017/01/about-chapter-300x300.png 300w, https://d2icp22po6iej.cloudfront.net/wp-content/uploads/2017/01/about-chapter-768x768.png 768w, https://d2icp22po6iej.cloudfront.net/wp-content/uploads/2017/01/about-chapter-1024x1024.png 1024w, https://d2icp22po6iej.cloudfront.net/wp-content/uploads/2017/01/about-chapter.png 1198w" sizes="(max-width: 150px) 100vw, 150px"></a></li>
</ul></div></div>
<aside id="chapter-top-sidebar" class="widget-area" original-class="widget-area" role="complementary"></aside><div class="wrapper" original-class="wrapper"><div class="innercontent" original-class="innercontent">
<div class="entry-content" original-class="entry-content"><?php require(DRUPAL_ROOT."/sites/all/themes/pgcalc_master/page.content.tpl.php"); ?></div>
<aside id="chapter-inner-sidebar" class="widget-area" original-class="widget-area" role="complementary"><div class="widget" original-class="widget"><?php print render($page['menu']); ?></div>
<div><div id="chapter-sidebar-donate">
<a href="https://www.apdaparkinson.org/1813d2l/" class="button-donate" original-class="button-donate">Donate Today</a>
</div></div></aside></div></div> </article></main></div>
<aside id="chapter-sidebar" class="widget-area" original-class="widget-area" role="complementary"><div id="chapter_content_widget-2" class=" widget chapter_contact_content" original-class=" widget chapter_contact_content"><div class="wrapper" original-class="wrapper">
<!----------------------------<div>
<h4 class="widgettitle" original-class="widgettitle"> Contact Northwest</h4>Email: <a href="mailto:apdanw@apdaparkinson.org">apdanw@apdaparkinson.org</a><br>Phone: <a href="tel://www.apdaparkinson.org/community/northwest/upcoming-events-3/+1-206-695-2905">206-695-2905</a><br>Fax: 206-455-8980<h5>Address:</h5>150 Nickerson Street<br>Suite 100<br>Seattle, WA 98109<p class="sidebar-social" original-class="sidebar-social" style="margin-top:2em;">
<a class="social" original-class="social" href="https://www.facebook.com/APDAnorthwest" target="_blank"><i class="fa fa-facebook" original-class="fa fa-facebook" aria-hidden="false"></i></a>
<a class="social" original-class="social" href="https://twitter.com/APDA_NW" target="_blank"><i class="fa fa-twitter" original-class="fa fa-twitter" aria-hidden="false"></i></a></p>
</div>-------------------------------------->
<div></div>
</div></div>
<div id="text-5" class="widget widget_text" original-class="widget widget_text"><div class="textwidget" original-class="textwidget">
<div class="doctor_prompt" original-class="doctor_prompt"><p><a href="https://www.apdaparkinson.org/resources-support/ask-the-doctor/" class="doctor" original-class="doctor">Ask a Doctor</a></p></div>
<div class="story_prompt" original-class="story_prompt"><p><a href="https://www.apdaparkinson.org/get-involved/share-your-story/" class="story" original-class="story">Share Your Story</a></p></div>
</div></div>
</aside></div>
<footer id="colophon" class="site-footer" original-class="site-footer" role="contentinfo"><div class="footer-widgets" original-class="footer-widgets"><div id="footer-sidebar" class="footer-sidebar widget-area wrapper" original-class="footer-sidebar widget-area wrapper" role="complementary">
<div id="nav_menu-2" class="widget widget_nav_menu" original-class="widget widget_nav_menu">
<h4 class="widgettitle" original-class="widgettitle">Quick Links</h4>
<div class="menu-footer-widget-menu-container" original-class="menu-footer-widget-menu-container"><ul id="menu-footer-widget-menu" class="menu" original-class="menu"><li id="menu-item-405" class="neural-icon menu-item menu-item-type-post_type menu-item-object-page menu-item-405" original-class="neural-icon menu-item menu-item-type-post_type menu-item-object-page menu-item-405"><a href="https://www.apdaparkinson.org/what-is-parkinsons/">Parkinson&rsquo;s Disease</a></li>
<li id="menu-item-404" class="resource-icon menu-item menu-item-type-post_type menu-item-object-page menu-item-404" original-class="resource-icon menu-item menu-item-type-post_type menu-item-object-page menu-item-404"><a href="https://www.apdaparkinson.org/resources-support/">Education &amp; Support</a></li>
<li id="menu-item-408" class="research-icon menu-item menu-item-type-custom menu-item-object-custom menu-item-408" original-class="research-icon menu-item menu-item-type-custom menu-item-object-custom menu-item-408"><a href="https://www.apdaparkinson.org/research/">Research</a></li>
<li id="menu-item-407" class="apda-icon menu-item menu-item-type-custom menu-item-object-custom menu-item-407" original-class="apda-icon menu-item menu-item-type-custom menu-item-object-custom menu-item-407"><a href="https://www.apdaparkinson.org/community/">APDA in your Community</a></li>
<li id="menu-item-403" class="walk-icon menu-item menu-item-type-post_type menu-item-object-page menu-item-403" original-class="walk-icon menu-item menu-item-type-post_type menu-item-object-page menu-item-403"><a href="https://www.apdaparkinson.org/get-involved/">Get Involved</a></li>
<li id="menu-item-406" class="contact-icon menu-item menu-item-type-custom menu-item-object-custom menu-item-406" original-class="contact-icon menu-item menu-item-type-custom menu-item-object-custom menu-item-406"><a href="https://www.apdaparkinson.org/contact/">Contact</a></li>
</ul></div>
</div>
<div id="text-3" class="widget widget_text" original-class="widget widget_text">
<h4 class="widgettitle" original-class="widgettitle">About APDA</h4>
<div class="textwidget" original-class="textwidget">
<p><a style="border-bottom:2px solid #ececec;" href="https://www.apdaparkinson.org/about-apda/">The American Parkinson Disease Association (APDA)</a> is the largest grassroots network dedicated to fighting Parkinson&rsquo;s disease (PD) and works tirelessly to assist the more than 1 million Americans with PD live life to the fullest in the face of this chronic, neurological disorder. Founded in 1961, APDA has raised and invested more than $170 million to provide outstanding patient services and educational programs, elevate public awareness about the disease, and support research designed to unlock the mysteries of PD and ultimately put an end to this disease.</p>
<div class="seals" original-class="seals">
<div class="charity-seal" original-class="charity-seal"><a class="guidestar" original-class="guidestar" href="https://www.guidestar.org/profile/13-1962771" target="_blank" rel="noopener"><img src="/sites/all/themes/apdaparkinson/img/gximage2"></a></div>
<div class="charity-seal" original-class="charity-seal"><img src="/sites/all/themes/apdaparkinson/img/charity-navigator-125x125.gif"></div>
</div>
</div>
</div>
<div id="text-2" class="widget widget_text" original-class="widget widget_text">
<h4 class="widgettitle" original-class="widgettitle">National Headquarters</h4>
<div class="textwidget" original-class="textwidget">
<p>135 Parkinson Avenue<br>
Staten Island, NY 10305<br>
TEL: 800-223-2732<br>
FAX: 718-981-4399<br><i class="fa fa-envelope" original-class="fa fa-envelope" aria-hidden="false"></i> <a href="mailto:apda@apdaparkinson.org?subject=Contact%20from%20website">apda@apdaparkinson.org</a></p>
<p><a class="social" original-class="social" href="https://www.facebook.com/APDA.INC" target="_blank"><i class="fa fa-facebook" original-class="fa fa-facebook" aria-hidden="false"></i></a> <a class="social" original-class="social" href="https://twitter.com/apdaparkinsons" target="_blank"><i class="fa fa-twitter" original-class="fa fa-twitter" aria-hidden="false"></i></a> <a class="social" original-class="social" href="https://www.youtube.com/user/APDAparkinson/videos" target="_blank"><i class="fa fa-youtube" original-class="fa fa-youtube" aria-hidden="false"></i></a><a class="social" original-class="social" href="https://www.linkedin.com/company/american-parkinson-disease-association" target="_blank"><i class="fa fa-linkedin" original-class="fa fa-linkedin" aria-hidden="false"></i></a></p>
</div>
</div>
</div></div>
<div class="menu-footer-container" original-class="menu-footer-container"><ul id="footer-menu-nav" class="menu" original-class="menu"><li id="menu-item-1479" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1479" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1479"><a href="https://www.apdaparkinson.org/privacy-policy/">Privacy Policy</a></li>
<li id="menu-item-1940" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1940" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1940"><a href="https://www.apdaparkinson.org/about-apda/financial-reports/">Financial Reports</a></li>
<li id="menu-item-1513" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1513" original-class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1513"><a href="https://www.apdaparkinson.org/about-apda/strategic-plan/">2015-18 Strategic Plan</a></li>
</ul></div>
<div class="site-info" original-class="site-info"><p>American Parkinson Disease Association is exempt from federal income taxes under Section 501(c)(3) of the Internal Revenue Code.<br>
&copy; <?php print variable_get('pgc_copyright_year'); ?> American Parkinson Disease Association. All Rights Reserved.</p></div>
<div class="footer-menu" original-class="footer-menu"></div>
</footer></div>
<div id="wpfront-scroll-top-container"><img src="/sites/all/themes/apdaparkinson/img/1.png" alt=""></div> <script type="text/javascript">function wpfront_scroll_top_init() {if(typeof wpfront_scroll_top == "function" && typeof jQuery !== "undefined") {wpfront_scroll_top({"scroll_offset":400,"button_width":0,"button_height":0,"button_opacity":0.8,"button_fade_duration":200,"scroll_duration":400,"location":1,"marginX":20,"marginY":20,"hide_iframe":"on","auto_hide":"on","auto_hide_after":5});} else {setTimeout(wpfront_scroll_top_init, 100);}}wpfront_scroll_top_init();</script><script type="text/javascript" src="/sites/all/themes/apdaparkinson/js/02e40.js"></script><script type="text/javascript" src="/sites/all/themes/apdaparkinson/js/d3.v3.min.js"></script><script type="text/javascript" src="/sites/all/themes/apdaparkinson/js/b287e.js"></script><script type="text/javascript">/* */
var simcal_default_calendar = {"ajax_url":"\/wp-admin\/admin-ajax.php","nonce":"75a622922b","locale":"en_US","text_dir":"ltr","months":{"full":["January","February","March","April","May","June","July","August","September","October","November","December"],"short":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]},"days":{"full":["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],"short":["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]},"meridiem":{"AM":"AM","am":"am","PM":"PM","pm":"pm"}};
var simcal_default_calendar = {"ajax_url":"\/wp-admin\/admin-ajax.php","nonce":"75a622922b","locale":"en_US","text_dir":"ltr","months":{"full":["January","February","March","April","May","June","July","August","September","October","November","December"],"short":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]},"days":{"full":["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],"short":["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]},"meridiem":{"AM":"AM","am":"am","PM":"PM","pm":"pm"}};
/* */</script><script type="text/javascript" src="/sites/all/themes/apdaparkinson/js/e5a2c.js"></script><script>svgeezy.init(false, 'png');</script></li>
</div>
</div>
</li>
</div>
</div>
</li>
</div>
</div>
</li>
</div>
</div>
</li></ul></div></nav></header></div>
</body>